<?php

/**
 * Implement hook_init
 */
function nhansu_chart_init() {
    drupal_add_js('https://www.google.com/jsapi');
    drupal_add_js(drupal_get_path('module','nhansu_chart').'/misc/chart.js');
}

function nhansu_chart_menu() {
    $items['nv/%/%'] = array(
        'title' => 'Thông tin',
        'page callback' => 'nhansu_get_data_kpi',
        'page arguments' => array(1,2),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    return $items;
}
/**
 * Implement hook_block_info
 */

function nhansu_chart_block_info() {
    $blocks['chart_colum_home'] = array(
        'info' => t('Chart KPI'),
    );
    $blocks['chart_xanhdovang'] = array(
        'info' => t('Xanh do vang'),
    );

    $blocks['home_giamdoc'] = array(
        'info' => t('Home cho Giám Đốc'),
    );
    $blocks['home_truongphong'] = array(
        'info' => t('Home cho Trưởng Phòng'),
    );
    $blocks['home_nhanvien'] = array(
        'info' => t('Home cho Nhân Viên'),
    );

    return $blocks;
}


function nhansu_chart_block_view($delta = '') {

    $block = array();
    switch ($delta) {
        case 'chart_colum_home':
            $block['content'] = nhansu_chart_colum();
            break;
        case 'chart_xanhdovang':
            $block['content'] = nhansu_char_xanhdovang();
            break;

        case 'home_giamdoc':
            $block['content'] = nhansu_chart_home_giamdoc();
            break;
        case 'home_truongphong':
            $block['content'] = nhansu_chart_home_truongphong();
            break;
        case 'home_truongphong':
            $block['content'] = nhansu_chart_home_nhanvien();
            break;
    }
    return $block;
}

function nhansu_chart_home_giamdoc() {
   $output = nhansu_chart_colum_giamdoc();
   return $output;
}


function nhansu_char_xanhdovang() {
    $toi_thieu = 100;
    $muc_tieu = 200;
    $thuc_hien = 150;
    $ouput = '<h2>Cảnh báo mức độ hoàn thành</h2>';
    if($thuc_hien < $toi_thieu) {
      $ouput .= ' <div class="canhbao_left">
                <ul>
                    <li class="do den_giaothong dat_chuan" style="background: red;width: 300px;height: 40px"></li>
                    <li class="vang den_giaothong" style="background: yellow;width: 300px;height: 40px"></li>
                    <li class="xanh den_giaothong" style="background: #008000;width: 300px;height: 40px"></li>
                </ul>
                </div>
                <div class="canhbao_right">Doanh thu của công ty đang ở mức nguy hiểm.</div>
      ';
    }
    elseif($thuc_hien < $muc_tieu && $thuc_hien > $toi_thieu ) {
        $ouput .= '
 <div class="canhbao_left">
                <ul>
                    <li class="do den_giaothong" style="background: red;width: 300px;height: 40px"></li>
                    <li class="vang den_giaothong dat_chuan" style="background: yellow;width: 300px;height: 40px"></li>
                    <li class="xanh den_giaothong" style="background: #008000;width: 300px;height: 40px"></li>
                </ul>
                 </div>
                <div class="canhbao_right">Doanh thu của công ty chưa đạt mục tiêu.</div>
      ';
    }
    else {
        $ouput .= '
                <div class="canhbao_left">
                <ul>
                    <li class="do den_giaothong" style="background: red;width: 300px;height: 40px"></li>
                    <li class="vang den_giaothong " style="background: yellow;width: 300px;height: 40px"></li>
                    <li class="xanh den_giaothong dat_chuan" style="background: #008000;width: 300px;height: 40px"></li>
                </ul>
                 </div>
                <div class="canhbao_right">Doanh thu của công ty đã đạt mục tiêu.</div>
      ';
    }
    return $ouput;
}

function nhansu_chart_colum_giamdoc() {
    $js =  '
        google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
        ["Đã giải ngân", "Chưa giải ngân"],
          '.nhansu_chart_data().'
        ]);

        var options = {
          is3D: true,
           chartArea:{top:10,bottom:50,left:10,right:150,width:"150%"},
        };

        var chart = new google.visualization.PieChart(document.getElementById("chart_div2"));
        chart.draw(data, options);
        }
    ';
    $block = module_invoke('nhansu_chart', 'block_view', 'chart_xanhdovang');
    $giao_thong =  render($block['content']);
    drupal_add_js($js, array('scope' => 'footer', 'type' => 'inline'));
    $form1 = drupal_get_form('nhansu_chart_form_select');
    $form = drupal_get_form('nhansu_chart_filer_time');
    $output = '<div class="filter_time">'.drupal_render($form).'</div>';
    $output .= '<div class="chart_reve">';
    $output .= drupal_render($form1);
    $output .= '</div>';
    $output .= '<div class="content_home1"> <div class="right_1"> <h2>Tỷ lệ hoàn thành chỉ tiêu</h2><div id="chart_div2" style="width:450px;height:300px;float:left"></div></div>';
    $output .= nhansu_chart_colum_chuan();
    $output .= '</div>';
    $output .= '<div id="clear" style="clear: both"></div>';
    $output .= $giao_thong;
    $output .= '<div id="clear" style="clear: both"></div>';
    $output .= '<div id="chart_colum1"><h2 id="tieu_colum"></h2><div id="chart_colum"></div></div>';
    $output .= '<div id="clear" style="clear: both"></div>';
    $output .= nhansu_chart_chitiet_home_thongke_giamdoc();
    return $output;
}



function nhansu_chart_colum() {
    $js =  '
        google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
        ["Đã giải ngân", "Chưa giải ngân"],
          '.nhansu_chart_data().'
        ]);

        var options = {
          is3D: true,
           chartArea:{top:10,bottom:50,left:10,right:150,width:"150%"},
        };

        var chart = new google.visualization.PieChart(document.getElementById("chart_div2"));
        chart.draw(data, options);
        }
    ';
    $block = module_invoke('nhansu_chart', 'block_view', 'chart_xanhdovang');
    $giao_thong =  render($block['content']);
    drupal_add_js($js, array('scope' => 'footer', 'type' => 'inline'));
    $header = array('KPI','Hoàn thành');
    $form1 = drupal_get_form('nhansu_chart_form_select');
    $form = drupal_get_form('nhansu_chart_filer_time');
    $output = '<div class="filter_time">'.drupal_render($form).'</div>';
    $output .= '<div class="chart_reve"><h2>Chỉ tiêu KPI</h2>';
    $output .= drupal_render($form1);
    $output .= '</div>';
    $output  .= '<div class="content_revenue" style ="width:280px;float:right;margin-right:35px;"><h2>Chi tiết</h2>'.theme('table', array('header' => $header,   'rows' => nhansu_data_table() )).'</div>';
    $output .= '<div class="content_home1"> <div id="chart_div2" style="width:640px;height:300px;float:left"></div>';
    $output .= '</div>';
    $output .= '<div id="clear" style="clear: both"></div>';
    $output .= $giao_thong;
    $output .= '<div id="clear" style="clear: both"></div>';
    $output .= '<div id="chart_colum1"><h2 id="tieu_colum"></h2><div id="chart_colum"></div></div>';
    return $output;
}

function nhansu_chart_list_roles($uid = null) {
    $query = db_query("SELECT nid, title FROM {node} WHERE type = :type",array(":type" => 'article'));
    foreach($query as $rows) {
        $res[$rows->nid] = $rows->title;
    }
    return $res;
}
function nhansu_chart_list_roles_extra() {
    $query = db_query("SELECT nid, title FROM {node} WHERE type = :type",array(":type" => 'article'));
    foreach($query as $rows) {
        $res[$rows->nid] = $rows -> title;
        $res[$rows->nid] = $rows -> title;
        $ress[] = $res;
    }
    $ress[] = $res;
    return $ress;
}

function nhansu_chart_list_all_user() {

}

function nhansu_chart_filer_time() {
    $timenow = time();
    $form = array();

    $form['from'] = array(
        '#type' => 'date_popup',
        '#title' => t('Từ ngày'),
        '#size' => 20,
        '#date_format' => 'd/m/Y',
        '#default_value' => date('c', strtotime($timenow)),
        '#date_year_range' => '-3:+3'
    );
    $form['to'] = array(
        '#type' => 'date_popup',
        '#title' => t('Tới'),
        '#size' => 20,
        '#date_format' => 'd/m/Y',
        '#default_value' => date('c', strtotime($timenow)),
        '#date_year_range' => '-3:+3'
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#attributes' => array('onclick' => 'return (false);'),
        '#value' => t('Xem'),
    );
    return $form;
}
function nhansu_chart_filer_time_validate($form, &$form_state) {
    $from = strtotime($form_state['values']['from']);
    $to = strtotime($form_state['values']['to']);
    $timenow = time();

    if (!$from && $to) {
        $from = $to;
    }

    if (!$to && $from) {
        $to = $from;
    }

    if ($from > $timenow || $from > $to) {
        form_set_error('Thời gian nhập vào không hợp lệ');
        return;
    }

    $query = 'from[date]=' . format_date($from, 'custom', 'm/d/Y') . '&to[date]='.format_date($to, 'custom', 'm/d/Y');
    $query = str_replace('/', '%2F', $query);
    drupal_goto('doji/thongke', $query);
}
function nhansu_chart_form_select() {
    $role = nhansu_kpi_check_user();
    $arr_pb = array('ALL'=>'-- Tất cả --') + nhansu_list_phong_ban();
    $arr = array('ALL'=>'-- Tất cả --') + nhansu_chart_list_roles();
    $form = array();
    if($role == 1){
            $form['selected_phong'] = array(
                '#title' => t('Phòng ban'),
                '#type' => 'select',
                '#options' => $arr_pb,
                '#attributes' => array(
                    'class' =>array('select_area'),
                ),
            );
        $form['selected'] = array(
            '#title' => t('Nhân viên'),
            '#type' => 'select',
            '#options' => $arr,
            '#attributes' => array(
                'class' =>array('select_nhanvien'),
            ),
        );
    }
   if($role == 2) {
       $arr1 = array('ALL'=>'-- Tất cả --') + nhansu_kpi_get_all_node_in_phong();
       $form['selected'] = array(
           '#title' => t('Nhân viên'),
           '#type' => 'select',
           '#options' => $arr1,
           '#attributes' => array(
               'class' =>array('select_nhanvien'),
           ),
       );
   }

    return $form;
}

function nhansu_chart_data($tid = null,$nid = null ) {
    $data = '';
    $cht = 0;
    if($tid == null){
        $role = nhansu_kpi_check_user();
        if($role == 1 || $role == 2) {
            $output = nhansu_kpi_get_all();
            foreach($output as $result) {
                $cht = $cht + $result['ht'];
            }
            $cht_ok = 100 - $cht;
            $data .= '[" ' . "Hoàn thành" . '", '. $cht . ' ],';
            $data .= '[" ' . "Chưa hoàn thành" . '", '. $cht_ok . ' ],';
            return $data;
            exit;
        }
        else{
            global $user;
            $uid = $user ->uid;
            $nid = nhansu_uid_to_nid($uid);
            $node = node_load($nid);
            $ctieu = $node ->field_chiteu['und'];
            foreach($ctieu as $k =>$result) {
                $node_dl = node_load($result['value']);
                $title = $node_dl -> title;
                $tt = $node ->field_toithieu['und'][$k]['value'];
                $mt = $node ->field_muctieu['und'][$k]['value'];
                $ht = $node->field_hoan_thanh['und'][$k]['value'];
                $ht = str_replace("%","",trim($ht));
                $cht = $cht + $ht;
            };
            $cht_ok = 100 - $cht;
            $data .= '[" ' . "Hoàn thành" . '", '. $cht . ' ],';
            $data .= '[" ' . "Chưa hoàn thành" . '", '. $cht_ok . ' ],';
            return $data;
        }
    }
    else {
        if($nid == 'ALL') {
            if($tid == 'ALL') {
                $output = nhansu_kpi_get_all();
                foreach($output as $result) {
                    $cht = $cht + $result['ht'];
                }
                $cht_ok = 100 - $cht;
                $data .= '[" ' . "Hoàn thành" . '", '. $cht . ' ],';
                $data .= '[" ' . "Chưa hoàn thành" . '", '. $cht_ok . ' ],';
                return $data;
            }
            else {
                $output = nhansu_kpi_get_all($tid);
                foreach($output as $result) {
                    $cht = $cht + $result['ht'];
                }
                $cht_ok = 100 - $cht;
                $data .= '[" ' . "Hoàn thành" . '", '. $cht . ' ],';
                $data .= '[" ' . "Chưa hoàn thành" . '", '. $cht_ok . ' ],';
                return $data;
            }
        }
        else {
            $nid = arg(2);
            $node = node_load($nid);
            $ctieu = $node ->field_chiteu['und'];
            foreach($ctieu as $k =>$result) {
                $node_dl = node_load($result['value']);
                $title = $node_dl -> title;
                $tt = $node ->field_toithieu['und'][$k]['value'];
                $mt = $node ->field_muctieu['und'][$k]['value'];
                $ht = $node->field_hoan_thanh['und'][$k]['value'];
                $ht = str_replace("%","",trim($ht));
                $cht = $cht + $ht;
            };
            $cht_ok = 100 - $cht;
            $data .= '[" ' . "Hoàn thành" . '", '. $cht . ' ],';
            $data .= '[" ' . "Chưa hoàn thành" . '", '. $cht_ok . ' ],';
            return $data;
        }

    }

}

function nhansu_data_table_home_giamdoc() {
    $output = nhansu_kpi_get_all();
    foreach($output as $k => $datas) {
        $node = node_load($datas['nid']);
        $thuc_hien = $datas['thuc_hien'];
        $toi_thieu = $datas['toi_thieu'];
        $muc_tieu = $datas['muc_tieu'];
        $row['title'] =  $node -> title;
        $row['muc_tieu'] = $muc_tieu;
        $row['toi_thieu'] = $toi_thieu;
        $row['thuc_hien'] = $thuc_hien;
        //$row['ht'] = round($datas['ht'],2).'%';
        $rows[] = $row;
    }
    return $rows;

}

function nhansu_data_table($tid = null, $nid = null) {
    if($tid == null) {
        $role = nhansu_kpi_check_user();
        if($role == 1 || $role == 2) {
            $output = nhansu_kpi_get_all();
            foreach($output as $k => $datas) {
                $node = node_load($datas['nid']);
                $thuc_hien = $datas['thuc_hien'];
                $toi_thieu = $datas['toi_thieu'];
                $muc_tieu = $datas['muc_tieu'];
                $row['title'] =  '<a href="#chart_div2"><span class= "ckpi" rel ="'.$k.'"
                thuc_hien = '.$thuc_hien.'
                toi_thieu = ' .$toi_thieu.'
                muc_tieu = ' .$muc_tieu.'
                id = "kpi_'.$k.'">' .$node->title.'</span></a>';
                $row['ht'] = round($datas['ht'],2).'%';
                $rows[] = $row;
            }
            return $rows;
            exit;
        }
        else {
            global $user;
            $uid = $user ->uid;
            $nid = nhansu_uid_to_nid($uid);
            $node = node_load($nid);
            $ctieu = $node ->field_chiteu['und'];
            foreach($ctieu as $k =>$result) {
                $node_dl = node_load($result['value']);
                $title = $node_dl -> title;
                $ht = $node->field_hoan_thanh['und'][$k]['value'];
                $thuc_hien = $node->field_thuc_hien['und'][$k]['value'];
                $toi_thieu = $node->field_toithieu['und'][$k]['value'];
                $muc_tieu = $node->field_muctieu['und'][$k]['value'];
                $row['title'] = '<a href="#chart_div2"><span toi_thieu="'.$toi_thieu.'" thuc_hien="'.$thuc_hien.'" muc_tieu ="'.$muc_tieu.'" class= "ckpi" rel ="'.$k.'" id = "kpi_'.$nid.'" alt = "'.$nid.'">' .$title.'</span></a>';
                $row['ht'] = $ht;
                $rows[] = $row;
            };
            return $rows;
        }
    }
    else {
        if($nid == 'ALL') {
            if($tid == 'ALL') {
                $output = nhansu_kpi_get_all();
                foreach($output as $datas) {
                    $node = node_load($datas['nid']);
                    $thuc_hien = $datas['thuc_hien'];
                    $toi_thieu = $datas['toi_thieu'];
                    $muc_tieu = $datas['muc_tieu'];
                    $row['title'] =  '<a href="#chart_div2"><span class= "ckpi" rel ="'.$k.'"
                thuc_hien = '.$thuc_hien.'
                toi_thieu = ' .$toi_thieu.'
                muc_tieu = ' .$muc_tieu.'
                id = "kpi_'.$k.'">' .$node->title.'</span></a>';
                    $row['ht'] = round($datas['ht'],2).'%';
                    $rows[] = $row;
                }
                return $rows;
            }
            else {

                $output = nhansu_kpi_get_all($tid);
                foreach($output as $k => $datas) {
                    $node = node_load($datas['nid']);
                    $thuc_hien = $datas['thuc_hien'];
                    $toi_thieu = $datas['toi_thieu'];
                    $muc_tieu = $datas['muc_tieu'];
                    $row['title'] =  '<a  href="#chart_div2"><span onclick = "nhansu_chart_data()" class= "ckpi" rel ="'.$k.'"
                thuc_hien = '.$thuc_hien.'
                toi_thieu = ' .$toi_thieu.'
                muc_tieu = ' .$muc_tieu.'
                id = "kpi_'.$k.'">' .$node->title.'</span></a>';
                    $row['ht'] = round($datas['ht'],2).'%';
                    $rows[] = $row;
                }

                return $rows;
            }

        }
        else {
            $nid = arg(2);
            $node = node_load($nid);
            $ctieu = $node ->field_chiteu['und'];
            foreach($ctieu as $k =>$result) {
                $node_dl = node_load($result['value']);
                $title = $node_dl -> title;
                $ht = $node->field_hoan_thanh['und'][$k]['value'];
                $thuc_hien = $node->field_thuc_hien['und'][$k]['value'];
                $toi_thieu = $node->field_toithieu['und'][$k]['value'];
                $muc_tieu = $node->field_muctieu['und'][$k]['value'];
                $row['title'] = '<a href="#chart_div2"><span onclick = "nhansu_chart_data()" contoi_thieu="'.$toi_thieu.'" thuc_hien="'.$thuc_hien.'" muc_tieu ="'.$muc_tieu.'" class= "ckpi" rel ="'.$k.'" id = "kpi_'.$nid.'" alt = "'.$nid.'">' .$title.'</span></a>';
                $row['ht'] = $ht;
                $rows[] = $row;
            };
            return $rows;
        }
    }

}

function nhansu_get_data_kpi($nid,$item) {
    $node = node_load($nid);
    $ctieu = $node ->field_chiteu['und'];
    foreach($ctieu as $k =>$result) {
        if($k == $item) {
        $tt = $node ->field_toithieu['und'][$item]['value'];
        $mt = $node ->field_muctieu['und'][$item]['value'];
        $thuchien = $node->field_thuc_hien['und'][$item]['value'];

        }
    };
   $tt = (float)$tt;
    if($tt >0){
        $mt = (float)$mt;
        $thuchien = (float)$thuchien;
        $row = array("",$tt,$mt,$thuchien);

    }
    else {
       if($thuchien == "yes") {
           $tt = 100;
           $mt = 100;
           $thuchien = 100;
           $row = array("",$tt,$mt,$thuchien);
           print json_encode($row);
           exit;
       }
        else{
            $tt = 100;
            $mt = 100;
            $thuchien = 0;
            $row = array("",$tt,$mt,$thuchien);

        }
    }
    print json_encode($row);
    exit;
}

function nhansu_chart_colum_chuan() {
    $js =  '
        google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([

          ["Element", "Doanh thu", { role: "style" } ],
        ["Mục tiêu", 2000, "color:#1222C0"],
        ["Tối thiểu", 1000, "color:#F00012"],
        ["Thực hiện", 1500, "color: #009ac3"]
        ]);
         var view = new google.visualization.DataView(data);
      view.setColumns([0, 1,
                       { calc: "stringify",
                         sourceColumn: 1,
                         type: "string",
                         role: "annotation" },
                       2]);

        var options = {
          is3D: true,
           chartArea:{top:10,bottom:50,left:10,right:150,width:"150%"},

        };

        var chart = new google.visualization.ColumnChart(document.getElementById("chart_div2_colum"));
      chart.draw(view, options);
        chart.draw(data, options);
        }
    ';

    drupal_add_js($js, array('scope' => 'footer', 'type' => 'inline'));
    $output = "<div class='right_2'>";
    $output .= '<h2 id="tieu_colum">Tiến độ thực hiện công việc</h2>';
    $output .= '<div id="chart_div2_colum" style="width:300px;height:300px;float:right"></div>';
    $output .= "</div>";
    return $output;
}

function nhansu_chart_chitiet_home_thongke_giamdoc() {
    drupal_set_title("");
    $output = '';
    $output .= '<h2>Thống kê chi tiết</h2>';
    $header = array('KPI','Tối thiểu',"Mục tiêu", "Thực hiện");
    $data = nhansu_data_table_home_giamdoc();
    $num = count($data);
    $tong_toi_thieu = 0;
    $tong_muc_tieu = 0;
    $tong_thuc_hien = 0;
    foreach($data as $content) {

        $giatri = $content['ht'];
        $giatri = trim(str_replace("%","",$giatri));
        $tong_toi_thieu = $tong_toi_thieu + $content['toi_thieu'];
        $tong_muc_tieu = $tong_muc_tieu + $content['muc_tieu'];
        $tong_thuc_hien = $tong_thuc_hien + $content['thuc_hien'];
        $tong_thuc_hien = $tong_thuc_hien + $content['thuc_hien'];
       // $tong = $tong + $giatri;
    }
   // $tong = $tong.'%';
    $arr_pb =  nhansu_data_table_home_giamdoc() + array($num => array("title" => "Tổng","toi_thieu" =>$tong_toi_thieu,"muc_tieu" =>$tong_muc_tieu,"thuc_hien" =>$tong_thuc_hien)) ;
    $output .= '<div class="noidung">'.theme('table', array('header' => $header,   'rows' => $arr_pb )).'</div>';
    $output .= '<div class="print_ex"><a onclick="chart_kpi_print(123)" href="#">Print</a> </div>';
    return $output;
}