<?php

/**
 * Implement hook_init
 */
function nhansu_chart_init() {
    drupal_add_js('https://www.google.com/jsapi');
    drupal_add_js(drupal_get_path('module','nhansu_chart').'/misc/chart.js');
}

function nhansu_chart_menu() {
    $items['nv/%/%'] = array(
        'title' => 'Thông tin',
        'page callback' => 'nhansu_get_data_kpi',
        'page arguments' => array(1,2),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    return $items;
}
/**
 * Implement hook_block_info
 */

function nhansu_chart_block_info() {
    $blocks['chart_colum_home'] = array(
        'info' => t('Chart KPI'),
    );
    $blocks['chart_xanhdovang'] = array(
        'info' => t('Xanh do vang'),
    );

    $blocks['home_giamdoc'] = array(
        'info' => t('Home cho Giám Đốc'),
    );
    $blocks['home_truongphong'] = array(
        'info' => t('Home cho Trưởng Phòng'),
    );
    $blocks['home_nhanvien'] = array(
        'info' => t('Home cho Nhân Viên'),
    );

    return $blocks;
}


function nhansu_chart_block_view($delta = '') {

    $block = array();
    switch ($delta) {
        case 'chart_colum_home':
            $block['content'] = nhansu_chart_colum();
            break;
        case 'chart_xanhdovang':
            $block['content'] = nhansu_char_xanhdovang();
            break;

        case 'home_giamdoc':
            $block['content'] = nhansu_chart_home_giamdoc();
            break;
        case 'home_truongphong':
            $block['content'] = nhansu_chart_home_truongphong();
            break;
        case 'home_nhanvien':
            $block['content'] = nhansu_chart_home_nhanvien();
            break;
    }
    return $block;
}

function nhansu_chart_home_giamdoc() {
   $output = nhansu_chart_colum_giamdoc();
   return $output;
}
function nhansu_chart_home_nhanvien() {
   $output = nhansu_chart_colum_nhanvien();
   return $output;
}

function nhansu_char_xanhdovang() {
    $role = nhansu_kpi_check_user();
    if($role !=3) {
        $du_lieu = doanhthu_for_giamdoc();
        $toi_thieu = $du_lieu['toi_thieu'];
        $thuc_hien = $du_lieu['thuc_hien'];
        $muc_tieu = $du_lieu['muc_tieu'];
    }
    if($role ==3) {
        global $user;
        $du_lieu = doanhthu_for_giamdoc(null,null,$user->uid);
        $toi_thieu = $du_lieu['toi_thieu'];
        $thuc_hien = $du_lieu['thuc_hien'];
        $muc_tieu = $du_lieu['muc_tieu'];
    }
    $ouput = '<h2>Cảnh báo mức độ hoàn thành</h2>';
    if($thuc_hien < $toi_thieu) {
      $ouput .= ' <div class="canhbao_left">
                <ul>
                    <li class="vang den_giaothong" style="background: yellow;width: 300px;height: 40px"></li>
                    <li class="do den_giaothong dat_chuan" style="background: red;width: 300px;height: 40px"></li>
                    <li class="xanh den_giaothong" style="background: #008000;width: 300px;height: 40px"></li>
                </ul>
                </div>
                <div class="canhbao_right">Doanh thu chưa đạt mức tối thiểu.</div>
      ';
    }
    elseif($thuc_hien <= $muc_tieu && $thuc_hien >= $toi_thieu ) {
        $ouput .= '
 <div class="canhbao_left">
                <ul>
                    <li class="do den_giaothong" style="background: red;width: 300px;height: 40px"></li>
                    <li class="vang den_giaothong dat_chuan" style="background: yellow;width: 300px;height: 40px"></li>
                    <li class="xanh den_giaothong" style="background: #008000;width: 300px;height: 40px"></li>
                </ul>
                 </div>
                <div class="canhbao_right">Doanh thu đã vượt qua mức tối thiểu nhưng chưa đạt mục tiêu.</div>
      ';
    }
    else {
        $ouput .= '
                <div class="canhbao_left">
                <ul>
                    <li class="do den_giaothong" style="background: red;width: 300px;height: 40px"></li>
                      <li class="xanh den_giaothong dat_chuan" style="background: #008000;width: 300px;height: 40px"></li>
                    <li class="vang den_giaothong " style="background: yellow;width: 300px;height: 40px"></li>

                </ul>
                 </div>
                <div class="canhbao_right">Doanh thu đã đạt mục tiêu. Thật tuyệt vời</div>
      ';
    }
    return $ouput;
}

function nhansu_chart_colum_giamdoc() {
    $table = nhansu_chart_data_table();
    $sum_toi_thieu = 0;
    $sum_muctieu = 0;
    $sum_thuc_hien = 0;
    $sum_hoan_thanh = 0;
    $count = count($table);
    foreach($table as $dlieu) {
        $sum_toi_thieu += $dlieu['toi_thieu'];
        $sum_muctieu += $dlieu['muc_tieu'];
        $sum_thuc_hien += $dlieu['thuc_hien'];
        $sum_hoan_thanh += substr($dlieu['hoanthanh'],0,-1);
    }
    $tong['title'] = "Tổng";
    $tong['toi_thieu'] = $sum_toi_thieu;
    $tong['muc_tieu'] = $sum_muctieu;
    $tong['thuc_hien'] = $sum_thuc_hien;
    $tong['hoanthanh'] = ($sum_hoan_thanh/$count).'%';
    array_push($table,$tong);
    $table_lef = nhansu_chart_data_table(1);
    $doanh_thu = doanhthu_for_giamdoc();

    $da_lam = $doanh_thu['thuc_hien'];
    $chua_lam = $doanh_thu['muc_tieu'] - $da_lam;
    $data = '  [" Đã thực hiện", '.$da_lam.' ],
          [" Còn lại", '.$chua_lam.' ],';
    $js =  '
        google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
        ["Đã giải ngân", "Chưa giải ngân"],'.$data.'
        ]);

        var options = {
          is3D: true,
           chartArea:{top:10,bottom:50,left:10,right:150,width:"150%"},
        };

        var chart = new google.visualization.PieChart(document.getElementById("chart_div2"));
        chart.draw(data, options);
        }
    ';
    $header = array('KPI','Hoàn thành');
    $block = module_invoke('nhansu_chart', 'block_view', 'chart_xanhdovang');
    $giao_thong =  render($block['content']);

    drupal_add_js($js, array('scope' => 'footer', 'type' => 'inline'));
    $form = drupal_get_form('nhansu_chart_filer_time');
    $output = '<div class="filter_time">'.drupal_render($form).'</div>';
    $output .= nhansu_chart_improve_kpi();
    if(!empty($table_lef))
    $output .= '<div class="content_home1"> <div class="right_1"> <h2>Tỷ lệ hoàn thành chỉ tiêu</h2><div id="chart_div2" style="width:450px;height:300px;float:left"></div></div>';
    if(!empty($table_lef))
    $output  .= '<div class="content_revenue" style ="width:280px;float:right;margin-right:35px;"><h2>Chi tiết</h2>'.theme('table', array('header' => $header,   'rows' => $table_lef )).'</div>';
    $output .= '</div>';
    $output .= '<div id="clear" style="clear: both"></div>';
    if(!empty($table_lef))
    $output .= $giao_thong;
    $output .= '<div id="clear" style="clear: both"></div>';
    $output .= '<div id="chart_colum1"><h2 id="tieu_colum"></h2><div id="chart_colum"></div></div>';
    $output .= '<div id="clear" style="clear: both"></div>';
    if(!empty($table_lef))
    $output .= '<h2>Thống kê chi tiết</h2>';
    $header_chitiet = array('KPI','Tối thiểu',"Mục tiêu", "Thực hiện","Hoàn thành");
    if(!empty($table))
    $output .= '<div class="noidung">'.theme('table', array('header' => $header_chitiet,   'rows' => $table )).'</div>';
    if(empty($table_lef)) {
        $output .= '<h3 style="text-align: center">Không có kết quả</h3>';
    }
    return $output;
}

function nhansu_chart_colum_nhanvien() {
    global $user;
    $table = nhansu_chart_data_table(null,$user->uid);
    $sum_toi_thieu = 0;
    $sum_muctieu = 0;
    $sum_thuc_hien = 0;
    $sum_hoan_thanh = 0;
    $count = count($table);
    foreach($table as $dlieu) {
        $sum_toi_thieu += $dlieu['toi_thieu'];
        $sum_muctieu += $dlieu['muc_tieu'];
        $sum_thuc_hien += $dlieu['thuc_hien'];
        $sum_hoan_thanh += substr($dlieu['hoanthanh'],0,-1);
    }
    $tong['title'] = "Tổng";
    $tong['toi_thieu'] = $sum_toi_thieu;
    $tong['muc_tieu'] = $sum_muctieu;
    $tong['thuc_hien'] = $sum_thuc_hien;
    $tong['hoanthanh'] = ($sum_hoan_thanh/$count).'%';
    array_push($table,$tong);
    $table_lef = nhansu_chart_data_table(1,$user->uid);
    $doanh_thu = doanhthu_for_giamdoc(null,null,$user->uid);
    $da_lam = $doanh_thu['thuc_hien'];
    $chua_lam = $doanh_thu['muc_tieu'] - $da_lam;
    $data = '  [" Đã thực hiện", '.$da_lam.' ],
          [" Còn lại", '.$chua_lam.' ],';
    $js =  '
        google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
        ["Đã giải ngân", "Chưa giải ngân"],'.$data.'
        ]);

        var options = {
          is3D: true,
           chartArea:{top:10,bottom:50,left:10,right:150,width:"150%"},
        };

        var chart = new google.visualization.PieChart(document.getElementById("chart_div2"));
        chart.draw(data, options);
        }
    ';
    $header = array('KPI','Hoàn thành');
    $block = module_invoke('nhansu_chart', 'block_view', 'chart_xanhdovang');
    $giao_thong =  render($block['content']);

    drupal_add_js($js, array('scope' => 'footer', 'type' => 'inline'));
    $form = drupal_get_form('nhansu_chart_filer_time');
    $output = '<div class="filter_time">'.drupal_render($form).'</div>';
    $output .= nhansu_chart_improve_kpi();
    if(!empty($table_lef))
        $output .= '<div class="content_home1"> <div class="right_1"> <h2>Tỷ lệ hoàn thành chỉ tiêu</h2><div id="chart_div2" style="width:450px;height:300px;float:left"></div></div>';
    if(!empty($table_lef))
        $output  .= '<div class="content_revenue" style ="width:280px;float:right;margin-right:35px;"><h2>Chi tiết</h2>'.theme('table', array('header' => $header,   'rows' => $table_lef )).'</div>';
    $output .= '</div>';
    $output .= '<div id="clear" style="clear: both"></div>';
    if(!empty($table_lef))
        $output .= $giao_thong;
    $output .= '<div id="clear" style="clear: both"></div>';
    $output .= '<div id="chart_colum1"><h2 id="tieu_colum"></h2><div id="chart_colum"></div></div>';
    $output .= '<div id="clear" style="clear: both"></div>';
    if(!empty($table_lef))
        $output .= '<h2>Thống kê chi tiết</h2>';
    $header_chitiet = array('KPI','Tối thiểu',"Mục tiêu", "Thực hiện","Hoàn thành");
    if(!empty($table))
        $output .= '<div class="noidung">'.theme('table', array('header' => $header_chitiet,   'rows' => $table )).'</div>';
    if(empty($table_lef)) {
        $output .= '<h3 style="text-align: center">Không có kết quả</h3>';
    }
    return $output;
}




function nhansu_chart_list_roles($uid = null) {
    $query = db_query("SELECT nid, title FROM {node} WHERE type = :type",array(":type" => 'article'));
    foreach($query as $rows) {
        $res[$rows->nid] = $rows->title;
    }
    return $res;
}
function nhansu_chart_list_roles_extra() {
    $query = db_query("SELECT nid, title FROM {node} WHERE type = :type",array(":type" => 'article'));
    foreach($query as $rows) {
        $res[$rows->nid] = $rows -> title;
        $res[$rows->nid] = $rows -> title;
        $ress[] = $res;
    }
    $ress[] = $res;
    return $ress;
}

function nhansu_chart_list_all_user() {

}

function nhansu_chart_filer_time($form, &$form_state) {
    $role = nhansu_kpi_check_user();
    $arr_pb = array(''=>'-- Tất cả --') + nhansu_list_phong_ban();
    $arr = array(''=>'-- Tất cả --') + nhansu_get_all_nhanvien();
    $cac_quy = array(
        '' => '--Quý--',
        1 => "Quý 1",
        2 => "Quý 2",
        3 => "Quý 3",
        4 => "Quý 4",
    );
    $curent_y = date("Y",time());
    $nam_quy = array(
        $curent_y => $curent_y,
        $curent_y-1 => $curent_y-1,
        $curent_y-2 => $curent_y-2,
        $curent_y-3 => $curent_y-3,
    );
    $from ="";
    $to = "";
    $value_quy = 0;
    $value_nam = 0;
    $loc_theo =  0;
    $format = 'Y-m-d';
    $value_phong = '';
    $value_nhanv = '';
    if(isset($_GET['loc_theo'])) {
          $from = $_GET['from_time'];
          $to  = $_GET['to_time'];
          $loc_theo = $_GET['loc_theo'];
          $value_quy = $_GET['cac_quy'];
          $value_nam = $_GET['nam_quy'];

    }

    $active = array(0 => t('Theo tháng'), 1 => t('Theo quý'));
    $form['loc_theo'] = array(
        '#type' => 'radios',
        '#title' => t('Lọc theo: '),
        '#default_value' => $loc_theo,
        '#options' => $active,
    );
    $form['cac_quy'] = array(
        '#title' => t('Chọn quý'),
        '#type' => 'select',
        '#options' => $cac_quy,
        '#attributes' => array(
            'class' =>array('select_area'),
        ),
        '#default_value' => $value_quy,
    );
    $form['nam_quy'] = array(
        '#title' => t('Chọn năm'),
        '#type' => 'select',
        '#options' => $nam_quy,
        '#default_value' => $value_nam,
        '#attributes' => array(
            'class' =>array('select_area'),
        ),
    );
    $form['from_time'] = array(
        '#type' => 'date_popup',
        '#title' => 'Từ ngày',
        '#default_value' => $from,
        '#date_format' => $format,
        '#date_label_position' => 'within',
        '#date_timezone' => 'Europe/Rome',
        '#date_increment' => 15,
        '#date_year_range' => '0:+2',
    );
    $form['to_time'] = array(
        '#type' => 'date_popup',
        '#title' => t('Tới ngày'),
        '#size' => 20,
        '#date_format' => $format,
        '#default_value' => $to,
        '#date_year_range' => '-3:+3'
    );
    //loc theo quyen
    if($role == 1){
        if(isset($_GET['loc_theo'])) {
            $value_phong = $_GET['phong_ban'];
            $value_nhanv = $_GET['nhan_vien'];
        }
        $form['selected_phong'] = array(
            '#title' => t('Phòng ban'),
            '#type' => 'select',
            '#options' => $arr_pb,
            '#default_value' => $value_phong,
            '#attributes' => array(
                'class' =>array('select_area'),
            ),
        );
        $form['selected'] = array(
            '#title' => t('Nhân viên'),
            '#type' => 'select',
            '#options' => $arr,
            '#default_value' => $value_nhanv,
            '#attributes' => array(
                'class' =>array('select_nhanvien'),
            ),
        );
    }
    if($role == 2) {
        $arr1 = array(''=>'-- Tất cả --') + nhansu_kpi_get_all_node_in_phong();
        $form['selected'] = array(
            '#title' => t('Nhân viên'),
            '#type' => 'select',
            '#options' => $arr1,
            '#default_value' => $value_nhanv,
            '#attributes' => array(
                'class' =>array('select_nhanvien'),
            ),
        );
    }

    $form['submit'] = array(
        '#type' => 'submit',
        //'#attributes' => array('onclick' => 'return (false);'),
        '#value' => t('Xem'),
    );
   return $form;
}
function nhansu_chart_filer_time_submit($form, &$form_state) {
    $path = current_path();
    $role = nhansu_kpi_check_user();
    if (isset($form_state['input'])) {
        $from_time = $form_state['input']['from_time']['date'];
        $to_time = $form_state['input']['to_time']['date'];
        $loc_theo = $form_state['input']['loc_theo'];
        $cac_quy = $form_state['input']['cac_quy'];
        $nam_quy = $form_state['input']['nam_quy'];
        if($role == 1) {
            $phong = $form_state['input']['selected_phong'];
            $nhan_vien = $form_state['input']['selected'];
            $form_state['redirect'] =  array(
                $path,
                array('query' => array(
                    'from_time' => $from_time,
                    'to_time' => $to_time,
                    'loc_theo' => $loc_theo,
                    'cac_quy' => $cac_quy,
                    'nam_quy' => $nam_quy,
                    'phong_ban' => $phong,
                    'nhan_vien' => $nhan_vien,
                )));
        }
        if($role == 2) {
            $nhan_vien = $form_state['input']['selected'];
            $form_state['redirect'] =  array(
                $path,
                array('query' => array(
                    'from_time' => $from_time,
                    'to_time' => $to_time,
                    'loc_theo' => $loc_theo,
                    'cac_quy' => $cac_quy,
                    'nam_quy' => $nam_quy,
                    'nhan_vien' => $nhan_vien,
                )));
        }
        if($role == 3) {
            $form_state['redirect'] =  array(
                $path,
                array('query' => array(
                    'from_time' => $from_time,
                    'to_time' => $to_time,
                    'loc_theo' => $loc_theo,
                    'cac_quy' => $cac_quy,
                    'nam_quy' => $nam_quy,
                )));
        }


    }
}
function nhansu_chart_form_select() {
    $role = nhansu_kpi_check_user();
    $arr_pb = array('ALL'=>'-- Tất cả --') + nhansu_list_phong_ban();
    $arr = array('ALL'=>'-- Tất cả --') + nhansu_chart_list_roles();
    $form = array();
    if($role == 1){
            $form['selected_phong'] = array(
                '#title' => t('Phòng ban'),
                '#type' => 'select',
                '#options' => $arr_pb,
                '#attributes' => array(
                    'class' =>array('select_area'),
                ),
            );
        $form['selected'] = array(
            '#title' => t('Nhân viên'),
            '#type' => 'select',
            '#options' => $arr,
            '#attributes' => array(
                'class' =>array('select_nhanvien'),
            ),
        );
    }
   if($role == 2) {
       $arr1 = array('ALL'=>'-- Tất cả --') + nhansu_kpi_get_all_node_in_phong();
       $form['selected'] = array(
           '#title' => t('Nhân viên'),
           '#type' => 'select',
           '#options' => $arr1,
           '#attributes' => array(
               'class' =>array('select_nhanvien'),
           ),
       );
   }

    return $form;
}


function nhansu_data_table_home_giamdoc() {
    $output = nhansu_kpi_get_all();
    foreach($output as $k => $datas) {
        $node = node_load($datas['nid']);
        $thuc_hien = $datas['thuc_hien'];
        $toi_thieu = $datas['toi_thieu'];
        $muc_tieu = $datas['muc_tieu'];
        $row['title'] =  $node -> title;
        $row['muc_tieu'] = $muc_tieu;
        $row['toi_thieu'] = $toi_thieu;
        $row['thuc_hien'] = $thuc_hien;
        //$row['ht'] = round($datas['ht'],2).'%';
        $rows[] = $row;
    }
    return $rows;

}


function nhansu_get_data_kpi($nid,$item) {
    $node = node_load($nid);
    $ctieu = $node ->field_chiteu['und'];
    foreach($ctieu as $k =>$result) {
        if($k == $item) {
        $tt = $node ->field_toithieu['und'][$item]['value'];
        $mt = $node ->field_muctieu['und'][$item]['value'];
        $thuchien = $node->field_thuc_hien['und'][$item]['value'];

        }
    };
   $tt = (float)$tt;
    if($tt >0){
        $mt = (float)$mt;
        $thuchien = (float)$thuchien;
        $row = array("",$tt,$mt,$thuchien);

    }
    else {
       if($thuchien == "yes") {
           $tt = 100;
           $mt = 100;
           $thuchien = 100;
           $row = array("",$tt,$mt,$thuchien);
           print json_encode($row);
           exit;
       }
        else{
            $tt = 100;
            $mt = 100;
            $thuchien = 0;
            $row = array("",$tt,$mt,$thuchien);

        }
    }
    print json_encode($row);
    exit;
}

function nhansu_chart_chitiet_home_thongke_giamdoc() {
    drupal_set_title("");
    $output = '';
    $output .= '<h2>Thống kê chi tiết. Đơn vị(Triệu đồng)</h2>';
    $header = array('KPI','Tối thiểu',"Mục tiêu", "Thực hiện");
    $data = nhansu_data_table_home_giamdoc();
    $data = array(
        0=> array(
            "title" => "Thanh toán phí cung cấp thông tin đến hạn",
            "muc_tieu" => 400,
            "toi_thieu" => 200,
            "thuc_hien" => 400,
            "ht" => "10"
        ),
        1=> array(
            "title" => "Doanh thu thuần hoạt động nghiệp vụ kế toán",
            "muc_tieu" => 500,
            "toi_thieu" => 300,
            "thuc_hien" => 400,
            "ht" => "15"
        ),
        2=> array(
            "title" => "Doanh thu thuần hoạt động nghiệp vụ giáo dục",
            "muc_tieu" => 600,
            "toi_thieu" => 400,
            "thuc_hien" => 400,
            "ht" => "10"
        ),
        3=> array(
            "title" => "Doanh thu thuần hoạt động nghiệp vụ tư vấn",
            "muc_tieu" => 500,
            "toi_thieu" => 100,
            "thuc_hien" => 300,
            "ht" => "20"
        ),
    );
    $num = count($data);
    $tong_toi_thieu = 0;
    $tong_muc_tieu = 0;
    $tong_thuc_hien = 0;
    foreach($data as $content) {
        $tong_toi_thieu = $tong_toi_thieu + $content['toi_thieu'];
        $tong_muc_tieu = $tong_muc_tieu + $content['muc_tieu'];
        $tong_thuc_hien = $tong_thuc_hien + $content['thuc_hien'];
    }
    $arr_pb =  $data + array($num => array("title" => "Tổng","toi_thieu" =>$tong_toi_thieu,"muc_tieu" =>$tong_muc_tieu,"thuc_hien" =>$tong_thuc_hien)) ;
    $output .= '<div class="noidung">'.theme('table', array('header' => $header,   'rows' => $arr_pb )).'</div>';
    return $output;
}

function nhansu_chart_chitiet_home_thongke_nhanvien() {
    $uid = 18;
    $nid = nhansu_get_nid_from_uid($uid,"giao_kpi");
    $node = node_load($nid);
    drupal_set_title("");
    $output = '';
    $output .= '<h2>Thống kê chi tiết. Đơn vị(Triệu đồng)</h2>';
    $header = array('KPI','Tối thiểu',"Mục tiêu", "Thực hiện");
    $arr = $node -> field_giaokpi_chi['und'];
    foreach($arr as $k =>$data) {

    }
    $output .= '<div class="noidung">'.theme('table', array('header' => $header,   'rows' => $arr_pb )).'</div>';
    return $output;
}
function nhansu_chart_data_nhanvien() {
    $uid = 18;
    $nid = nhansu_get_nid_from_uid($uid,'giao_kpi');
    $node = node_load($nid);
    $count = $node-> field_giaokpi_chi['und'];
    $ht = 0;
    foreach($count as $k => $data) {
        $hoan_thanh = trim($node -> field_giaokpi_hoanthanh['und'][$k]['value']);
        $hoan_thanh = substr($hoan_thanh,0,-1);
        $ht = $ht + $hoan_thanh;
    }
    $cht = 100 - $ht;
    $data = '  [" Hoàn thành", '.$ht.' ],
          [" Chưa hoàn thành", '.$cht.' ],';
    return $data;
}
function nhansu_data_table_nhanvien($tid = null, $nid = null) {
    $uid = 18;
    $nid = nhansu_get_nid_from_uid($uid,"giao_kpi");
    $node = node_load($nid);
    $ctieu = $node ->field_giaokpi_chi['und'];
    foreach($ctieu as $k =>$result) {
        $node_dl = node_load($result['value']);
        $title = $node_dl -> title;
        $ht = $node->field_giaokpi_hoanthanh['und'][$k]['value'];
        $thuc_hien = $node->field_giaokpi_thuchien['und'][$k]['value'];
        $toi_thieu = $node->field_giaokpi_toi['und'][$k]['value'];
        $muc_tieu = $node->field_giaokpi_muctieu['und'][$k]['value'];
        $row['title'] = '<a href="#chart_div2"><span toi_thieu="'.$toi_thieu.'" thuc_hien="'.$thuc_hien.'" muc_tieu ="'.$muc_tieu.'" class= "ckpi" rel ="'.$k.'" id = "kpi_'.$nid.'" alt = "'.$nid.'">' .$title.'</span></a>';
        $row['ht'] = $ht;
        $rows[] = $row;
    };
    return $rows;
}

function nhansu_chart_data_table($left = null,$nhan_vien = null) {
  $vid = doanhthu_for_giamdoc(1);
  $and = " AND nhom.field_giaokpi_nhom_value = 4 AND toithieu.delta = muctieu.delta AND thuchien.delta = muctieu.delta AND nhom.delta = muctieu.delta AND chi.delta =muctieu.delta";
  if(isset($_GET['nhan_vien'])) {
     $and = " AND toithieu.delta = muctieu.delta AND thuchien.delta = muctieu.delta AND nhom.delta = muctieu.delta AND chi.delta =muctieu.delta";
  }
  if(isset($nhan_vien)) {
     $and = " AND nguoidung.field_uid_value = ".$nhan_vien." AND toithieu.delta = muctieu.delta AND thuchien.delta = muctieu.delta AND nhom.delta = muctieu.delta AND chi.delta =muctieu.delta";
  }
  $sql = "
            SELECT SUM(muctieu.field_giaokpi_muctieu_value) as mtieu,SUM(toithieu.field_giaokpi_toi_value) as tthieu, SUM(thuchien.field_giaokpi_thuchien_value) as thien, chi.field_giaokpi_chi_value as nid
                    FROM {field_revision_field_giaokpi_muctieu} AS muctieu
                    INNER JOIN {field_revision_field_giaokpi_nhom} AS nhom ON muctieu.revision_id = nhom.revision_id
                    INNER JOIN {field_revision_field_giaokpi_toi} AS toithieu ON toithieu.revision_id = nhom.revision_id
                    INNER JOIN {node_revision} as nv ON nv.vid = toithieu.revision_id
                    INNER JOIN {field_revision_field_giaokpi_chi} as chi ON chi.revision_id = toithieu.revision_id
                    INNER JOIN {field_revision_field_kpi_giao_tu} AS tu ON tu.revision_id = toithieu.revision_id
                    INNER JOIN {field_revision_field_giao_kpi_den} AS den ON den.revision_id = tu.revision_id
                    INNER JOIN {field_data_field_uid} AS nguoidung ON nguoidung.entity_id = nv.nid
                    INNER JOIN {field_data_field_phongban} AS phong ON phong.entity_id = nguoidung.field_uid_value
                    INNER JOIN {field_revision_field_giaokpi_thuchien} AS thuchien ON thuchien.revision_id = den.revision_id
                    WHERE nv.vid IN (".$vid.")".$and." GROUP BY chi.field_giaokpi_chi_value
         ";
    $query = db_query($sql);
    $count = $query-> rowCount();
    if($count == 0) {
        return "";
        exit;
    }
    foreach($query as $data) {
        $row['title'] = nhansu_get_title_from_nid($data->nid);
        $row['toi_thieu'] = $data->tthieu;
        $row['muc_tieu'] = $data->mtieu;
        $row['thuc_hien'] = $data->thien;


        $row_left['title'] = nhansu_get_title_from_nid($data->nid);
        $hoan_thanh = ($data->thien - $data->tthieu)/($data->mtieu - $data->tthieu)*100;
        if($hoan_thanh < 0)
            $hoan_thanh = 0;
        else
            $hoan_thanh = round($hoan_thanh);
        $row['hoanthanh'] = $hoan_thanh.'%';
        $rows[] = $row;
        $row_left['hoanthanh'] = $hoan_thanh.'%';
        $row_lefts[] = $row_left;
    }
    if(isset($left))
        return $row_lefts;
    return $rows;
}

function nhansu_chart_improve_kpi(){
    global $base_url;
    global $user;
    $role = nhansu_kpi_check_user();
    if($role == 3) {
        $output = '<div class="improve"><a href="'.$base_url.'/nhanvien/'.$user->uid.'/kpi">Improve KPI</a> </div>';
    }
    else {
        $output = '<div class="improve"><a href="'.$base_url.'/quanly/kpi">Improve KPI</a> </div>';
    }
    return $output;
}