<?php

/**
 * Implement hook_init
 */
function nhansu_chart_init() {
    drupal_add_js('https://www.google.com/jsapi');
    drupal_add_js(drupal_get_path('module','nhansu_chart').'/misc/chart.js');
}

/**
 * Implement hook_block_info
 */

function nhansu_chart_block_info() {
    $blocks['chart_colum_home'] = array(
        'info' => t('Chart KPI'),
    );

    return $blocks;
}

function nhansu_chart_menu() {
    $items['nv/%/%'] = array(
        'title' => 'Thông tin',
        'page callback' => 'nhansu_get_data_kpi',
        'page arguments' => array(1,2),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
 return $items;
}

function nhansu_chart_block_view($delta = '') {
    $block = array();
    switch ($delta) {
        case 'chart_colum_home':
            $block['content'] = nhansu_chart_colum();
            break;
    }
    return $block;
}

function nhansu_chart_colum() {
    $js =  '
        google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
        ["Đã giải ngân", "Chưa giải ngân"],
          '.nhansu_chart_data().'
        ]);

        var options = {
          is3D: true,
           chartArea:{left:180,top:60,right:10,width:"150%"},
        };

        var chart = new google.visualization.PieChart(document.getElementById("chart_div2"));
        chart.draw(data, options);
        }
    ';
    drupal_add_js($js, array('scope' => 'footer', 'type' => 'inline'));
    $header = array('KPI','Hoàn thành');
   // $form1 = drupal_get_form('duhoc_chart_form_select');
    $output = '<div class="chart_reve"><h2>Chỉ tiêu KPI</h2>';
    //$output .= drupal_render($form1);
    $output .= '</div>';
    $output .= '<div class="content_home1"> <div id="chart_div2" style="width:740px;height:330px;float:left"></div>';
    $output  .= '<div class="content_revenue" style ="width:200px;float:right;"><h2>Chi tiết</h2>'.theme('table', array('header' => $header,   'rows' => nhansu_data_table() )).'</div>';
    $output .= '</div>';
    $output .= '<div id="clear" style="clear: both"></div>';
    $output .= '<div id="chart_colum1"><h2 id="tieu_colum"></h2><div id="chart_colum"></div></div>';
    return $output;
}

function nhansu_chart_list_roles() {
    $query = db_query("SELECT * FROM {role} WHERE rid > 3");
    foreach($query as $rows) {
        $res[$rows->rid] = $rows->name;
    }
    return $res;
}

function nhansu_chart_form_select() {
    global $user;
    $arr = array_merge(array('ALL'=>'-- cv --'),nhansu_chart_list_roles() );
    $form = array();
    $form['selected'] = array(
        '#type' => 'select',
        '#options' => $arr,
        '#attributes' => array(
            'class' =>array('select_area'),
        ),
    );
    return $form;
}

function nhansu_chart_data() {
    $node = node_load(7);
    $ctieu = $node ->field_chiteu['und'];
    $data = '';
    $cht = 0;
    foreach($ctieu as $k =>$result) {
      $node_dl = node_load($result['value']);
      $title = $node_dl -> title;
      $tt = $node ->field_toithieu['und'][$k]['value'];
      $mt = $node ->field_muctieu['und'][$k]['value'];
      $ht = $node->field_hoan_thanh['und'][$k]['value'];
      $ht = str_replace("%","",trim($ht));
      $cht = $cht + $ht;
    };
    $cht_ok = 100 - $cht;

    $data .= '[" ' . "Hoàn thành" . '", '. $cht . ' ],';
    $data .= '[" ' . "Chưa hoàn thành" . '", '. $cht_ok . ' ],';
return $data;
}

function nhansu_data_table() {
    $nid = 7;
    $uid = nhansu_nid_to_uid($nid);
    $node = node_load(7);
    $ctieu = $node ->field_chiteu['und'];
    foreach($ctieu as $k =>$result) {
        $node_dl = node_load($result['value']);
        $title = $node_dl -> title;
        $ht = $node->field_hoan_thanh['und'][$k]['value'];
        $row['title'] = '<a href="#chart_div2"><span class= "ckpi" rel ="'.$k.'" id = "kpi_'.$nid.'" alt = "'.$uid.'">' .$title.'</span></a>';
        $row['ht'] = $ht;
        $rows[] = $row;
    };
    return $rows;
}

function nhansu_get_data_kpi($nid,$item) {
    $node = node_load($nid);
    $ctieu = $node ->field_chiteu['und'];
    foreach($ctieu as $k =>$result) {
        if($k == $item) {
        $tt = $node ->field_toithieu['und'][$item]['value'];
        $mt = $node ->field_muctieu['und'][$item]['value'];
        $thuchien = $node->field_thuc_hien['und'][$item]['value'];

        }
    };
   $tt = (float)$tt;
   $mt = (float)$mt;
   $thuchien = (float)$thuchien;
   $row = array("",$tt,$mt,$thuchien);

   print json_encode($row);
   exit;
}