<?php

/**
 * Implement hook_init
 */
function nhansu_init() {
    if(isset($_POST['ajax_html_ids'])) {
        unset($_POST['ajax_html_ids']);
    }
    drupal_add_js(drupal_get_path('module','nhansu').'/js/script.js');
}

function nhansu_menu() {
    $items['nhanvien/%/info'] = array(
        'title' => 'Thông tin',
        'page callback' => 'nhansu_info',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['nhanvien/%/kpi'] = array(
        'title' => 'KPI',
        'page callback' => 'nhansu_info',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 1,
    );
    $items['quanly/nhanvien'] = array(
        'title' => 'Nhân Viên',
        'page callback' => 'nhansu_list_student',
        'access arguments' => array('access content'),
        'type' =>  MENU_LOCAL_TASK,
        'weight' => 1,
    );
    $items['quanly/test'] = array(
        'title' => 'Nhân Viên',
        'page callback' => 'nhansu_list_uid',
        'access arguments' => array('access content'),
        'type' =>  MENU_LOCAL_TASK,
        'weight' => 1,
    );
    $items['kpi/%'] = array(
        'title' => '',
        'page callback' => 'nhansu_get_kpi',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
    );
    $items['api/term/%'] = array(
        'title' => '',
        'page callback' => 'nhansu_list_node_term',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}
function nhansu_list_student() {
    global $base_url;
    $output = views_embed_view('nhanvien','default');
    return $output;
}
function nhansu_info($id='') {
    module_load_include('inc', 'node', 'node.pages');
    $node = node_load($id);
    $form = node_page_edit($node);
    // $form = '<div class="clear-form goldprice-sxht">' . $form . '</div>';
    if(arg(2) =='info'){
        drupal_set_title(t('Sơ yếu lý lịch'));
    }
    if(arg(2) == 'kpi') {
        drupal_set_title(t('Chỉ tiêu KPI'));
    }
    return $form;
}
function nhansu_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'article_node_form') {
    $form['field_nghenghiep']['#prefix'] ='<div class="group_info">Thông tin về chuyên môn nghiệp vụ:</div>';
    $form['field_image']['#prefix'] = '<div class="group_info">Thông tin cơ bản:</div>';
    $form['field_lyluan_chinhtri']['#prefix'] = '<div class="group_info">Chính trị:</div>';
    $form['field_ngoaingu']['#prefix'] = '<div class="group_info">Tin học/Ngoại ngữ:</div>';
    $form['field_suckhoe']['#prefix'] = '<div class="group_info">Sức khỏe:</div>';


    $form['fgm_node_article_form_group_qhgd_banthan']['#prefix'] = '<div class="group_info"> Quan hệ gia đình</div><div id="fgm_node_article_form_group_qhgd_banthan-add-more-wrapper"><h3> Về bản thân: Cha, Mẹ, Vợ (hoặc chồng), các con, anh chị em ruột</h3>';
    $form['fgm_node_article_form_group_benvo']['#prefix'] = '<div id="fgm_node_article_form_group_benvo-add-more-wrapper"><h3> Về bên vợ (hoặc chồng): Cha, Mẹ, anh chị em ruột</h3>';
      $form['field_xa']['#prefix'] = '<div class="clrb" style="height: 20px"></div><h3 class="h3-float">Nơi sinh: </h3>';
      $form['field_xa_que']['#prefix'] = '<h3 class="h3-float"> Quê quán: </h3>';
      $form['fgm_node_article_form_group_daotao']['#prefix'] = '<div id="fgm_node_article_form_group_daotao-add-more-wrapper"><div class="group_info">  Đào tạo, bồi dưỡng về chuyên môn, nghiệp vụ, lý luận chính trị, ngoại ngữ, tin học</div>';
      $form['fgm_node_article_form_group_daotao']['#suffix'] ='</div><h4>Ghi chú: Hình thức đào tạo: Chính quy, tại chức, chuyên tu, bồi dưỡng ..../ Văn bằng: TSKH, TS, Ths, Cử nhân, Kỹ sư ............</h4>';

      $form['fgm_node_article_form_group_congtac']['#prefix'] ='<div id="fgm_node_article_form_group_congtac-add-more-wrapper"><div class="group_info">  Tóm tắt quá trình công tác</div>';

      if(arg(2) == 'info') {
          if(!isset($form_state['build_info']['files'])){
              $form_state['build_info']['files'] = array("menu" => "modules/node/node.pages.inc");
          }
          $form['fgm_node_article_form_group_chiteu']['#access'] = false;
      }
      if(arg(2) == 'kpi') {

          if(!isset($form_state['build_info']['files'])){
              $form_state['build_info']['files'] = array("menu" => "modules/node/node.pages.inc");
          }
          $form['field_is_poster']['#access'] = FALSE;
          $form['fgm_node_article_form_group_chiteu']['#access'] = true;
      }
    }
}

function nhansu_form_node_form_alter(&$form, &$form_state) {
    if(arg(2) == 'kpi') {
        field_group_hide_field_groups($form, array('group_soyeu'));
    }
}

function nhansu_list_node_term() {
    $tid = arg(2);
    $node = taxonomy_select_nodes($tid);
    print json_encode($node);
    exit;

}
function nhansu_list_nhom_chitieu() {
    $name = 'nhom_chiteu';
    $myvoc = taxonomy_vocabulary_machine_name_load($name);
    $tree = taxonomy_get_tree($myvoc->vid);
    foreach ($tree as $term) {
        $row[$term->tid] = $term -> name;
    }
    return $row;

}

function nhansu_get_phongban() {
    global $user;
    $uid = $user ->uid;
    $query = db_query("SELECT field_phongban_tid FROM {field_data_field_phongban} WHERE entity_id =:uid",array(':uid' =>$uid));
}

function nhansu_list_node_kpi() {
    $query = db_query("SELECT nid,title FROM {node} WHERE type =:type",array(':type' => 'kpi'));
    foreach($query as $result) {
        $row[$result->nid] = $result -> title;
        $rows[] = $row;
    }
    return $rows;
}

function nhansu_get_kpi() {
    $nid = arg(1);
    $node = node_load($nid);
    $dv = '';
    $ts = '';
    $mt = '';
    $th = '';
    if(isset($node ->field_donvi_kpi['und'][0]['value']))
        $dv = $node ->field_donvi_kpi['und'][0]['value'];
    if(isset($node ->field_trongso_kpi['und'][0]['value']))
        $ts = $node ->field_trongso_kpi['und'][0]['value'];
    if(isset($node ->field_muctieu_kpi['und'][0]['value']))
        $mt = $node ->field_muctieu_kpi['und'][0]['value'];
    if(isset($node ->field_toithieu_kpi['und'][0]['value']))
        $th = $node ->field_toithieu_kpi['und'][0]['value'];
    $row  = array(
        '0' => $dv,
        '1' => $ts,
        '2' => $th,
        '3' => $mt,
    );
    print json_encode($row);
   exit;

}