<?php
function nhansu_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'article_node_form') {
    dpm($form);
    $form['fgm_node_article_form_group_qhgd_banthan']['#prefix'] = '<h1>30) Quan hệ gia đình</h1><div id="fgm_node_article_form_group_qhgd_banthan-add-more-wrapper"><h3> a) Về bản thân: Cha, Mẹ, Vợ (hoặc chồng), các con, anh chị em ruột</h3>';
    $form['fgm_node_article_form_group_benvo']['#prefix'] = '<div id="fgm_node_article_form_group_benvo-add-more-wrapper"><h3> b) Về bên vợ (hoặc chồng): Cha, Mẹ, anh chị em ruột</h3>';
      $form['field_xa']['#prefix'] = '<h3>4) Nơi sinh: </h3>';
      $form['field_xa_que']['#prefix'] = '<h3>5) Quê quán: </h3>';
      $form['fgm_node_article_form_group_daotao']['#prefix'] = '<div id="fgm_node_article_form_group_daotao-add-more-wrapper"><h3>  27) Đào tạo, bồi dưỡng về chuyên môn, nghiệp vụ, lý luận chính trị, ngoại ngữ, tin học</h3>';
      $form['fgm_node_article_form_group_daotao']['#suffix'] ='</div><h4>Ghi chú: Hình thức đào tạo: Chính quy, tại chức, chuyên tu, bồi dưỡng ..../ Văn bằng: TSKH, TS, Ths, Cử nhân, Kỹ sư ............</h4>';

      $form['fgm_node_article_form_group_congtac']['#prefix'] ='<div id="fgm_node_article_form_group_congtac-add-more-wrapper"><h3> 28) Tóm tắt quá trình công tác</h3>';
  

    }

}
