<?php

/**
 * Implement hook_init
 */
function nhansu_init() {
    if(isset($_POST['ajax_html_ids'])) {
        unset($_POST['ajax_html_ids']);
    }
    drupal_add_js(drupal_get_path('module','nhansu').'/js/script.js');
}

function nhansu_menu() {
    $items['nhanvien/%/info'] = array(
        'title' => 'Thông tin',
        'page callback' => 'nhansu_info',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['nhanvien/%/kpi'] = array(
        'title' => 'KPI',
        'page callback' => 'nhansu_info_kpi',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 1,
    );
    $items['nhanvien/%/kpi/add'] = array(
        'title' => 'KPI',
        'page callback' => 'nhansu_kpi_create',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 1,
    );

    $items['quanly/thongtin'] = array(
        'title' => 'Thông tin nhân sự',
        'page callback' => 'nhansu_list_student',
        'access arguments' => array('access content'),
        'type' =>  MENU_LOCAL_TASK,
        'weight' => 1,
    );
    $items['quanly/kpi'] = array(
        'title' => 'Giao KPI',
        'page callback' => 'nhansu_giao_kpi',
        'access arguments' => array('access content'),
        'type' =>  MENU_LOCAL_TASK,
        'weight' => 1,
    );
    $items['quanly/kpi/giao'] = array(
        'title' => 'Giao KPI',
        'page callback' => 'nhansu_giao_kpi',
        'access arguments' => array('access content'),
        'type' =>  MENU_LOCAL_TASK,
        'weight' => 1,
    );
    $items['quanly/kpi/kiemsoat'] = array(
        'title' => 'Kiểm soát KPI',
        'page callback' => 'nhansu_kpi_kiemsoat',
        'access arguments' => array('access content'),
        'type' =>  MENU_LOCAL_TASK,
        'weight' => 2,
    );
    $items['quanly/kpi/danhgia'] = array(
        'title' => 'Đánh giá KPI',
        'page callback' => 'nhansu_kpi_danhgia',
        'access arguments' => array('access content'),
        'type' =>  MENU_LOCAL_TASK,
        'weight' => 3,
    );

    $items['quanly/test'] = array(
        'title' => 'Nhân Viên',
        'page callback' => 'nhansu_list_uid',
        'access arguments' => array('access content'),
        'type' =>  MENU_LOCAL_TASK,
        'weight' => 1,
    );
    $items['kpi/%'] = array(
        'title' => '',
        'page callback' => 'nhansu_get_kpi',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
    );
    $items['api/term/%'] = array(
        'title' => '',
        'page callback' => 'nhansu_list_node_term',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
    );
    $items['home'] = array(
        'title' => '',
        'page callback' => 'nhansu_home',
        'access arguments' => array('access content'),
        'type' =>  MENU_LOCAL_TASK,
        'weight' => 1,
    );
    return $items;
}


function nhansu_info_kpi() {
    $role = nhansu_kpi_check_user();
    if($role == 3) {
        $id = nhansu_get_nid_from_uid(arg(1),'giao_kpi');
        $form = views_embed_view('kpi_user','default',$id);
    }
    else {
        $uid = arg(1);
        $id = nhansu_get_nid_from_uid($uid,"giao_kpi");
        module_load_include('inc', 'node', 'node.pages');
        $node = node_load($id);
        $form = node_page_edit($node);
        $uid = $form['field_giaokpi_nguoigiao']['und'][0]['value']['#default_value'];
        if($uid)
            $user_giao = user_load($uid);
        else
            $user_giao = user_load(1);
        $form['field_uid']['und']['#prefix'] .= '<div id="field-uid-add-more-wrapper"><div class="nguoi_giao"><span>Người giao:</span>'.$user_giao -> name.'</div><div class="nguoi_giao"><span>Người nhận:</span>'.nhansu_get_title_from_uid(arg(1)).'</div>';
    }
    drupal_set_title(t('Chỉ tiêu KPI'));
    return $form;
}
function nhansu_list_student() {
    global $base_url;
    $form = drupal_get_form('nhansu_chart_form_select');
    $output = drupal_render($form);
    $output = views_embed_view('thongtin_nhanvien','default');
    return $output;
}

function nhansu_giao_kpi() {
    //$form = drupal_get_form('nhansu_chart_form_select');
   // $output = drupal_render($form);
    $output = views_embed_view('nhanvien_kpi','default');
    return $output;
}
function nhansu_home() {
    return "";
}
function nhansu_info() {
    $uid = arg(1);
    $id = nhansu_get_nid_from_uid($uid,"article");
    module_load_include('inc', 'node', 'node.pages');
    $node = node_load($id);
    $form = node_page_edit($node);
    // $form = '<div class="clear-form goldprice-sxht">' . $form . '</div>';
    if(arg(2) =='info'){
        drupal_set_title(t('Sơ yếu lý lịch'));
    }
    if(arg(2) == 'kpi') {
        drupal_set_title(t('Chỉ tiêu KPI'));
    }
    return $form;
}
function nhansu_form_alter(&$form, &$form_state, $form_id) {
    if($form_id == 'kpi_node_form' && arg(1) == 'kpi') {
        global $base_url;
        $form['actions']['delete']['#access'] = FALSE;
        $delete ="<a href='".$base_url."/caidat/kpi/admin/".arg(3)."/delete'>Delete</a>";
        $form['actions']['submit']["#suffix"] = $delete;
    }
  if($form_id == "giao_kpi_node_form") {
      $role = nhansu_kpi_check_user();
      if(arg(2) == 'kpi') {
          $add = arg(3);
          if($role != 3) {

         //$form['field_uid']['#access'] = FALSE;
          $form['title']['#access'] = FALSE;
          $form['field_giaokpi_nguoigiao']['#access'] = FALSE;
          if(!isset($form_state['build_info']['files'])){
              $form_state['build_info']['files'] = array("menu" => "modules/node/node.pages.inc");
              }
          }
          if(isset($add) && $add =='add') {
              $form['title']['#access'] = FALSE;
          }
      }

  }
  if($form_id == 'article_node_form') {
     $check = nhansu_kpi_check_user();
      if($check == 3) {
          $form['actions']['#access'] = false;
          $form['actions']['#access'] = false;
          $form['field_gan_cho']['#access'] = false;
          $form['field_giaokpi_nguoigiao']['#access'] = false;
      }
    $form['field_nghenghiep']['#prefix'] ='<div class="group_info">Thông tin về chuyên môn nghiệp vụ:</div>';
    $form['field_image']['#prefix'] = '<div class="group_info">Thông tin cơ bản:</div>';
    $form['field_lyluan_chinhtri']['#prefix'] = '<div class="group_info">Chính trị:</div>';
    $form['field_ngoaingu']['#prefix'] = '<div class="group_info">Tin học/Ngoại ngữ:</div>';
    $form['field_suckhoe']['#prefix'] = '<div class="group_info">Sức khỏe:</div>';


    $form['fgm_node_article_form_group_qhgd_banthan']['#prefix'] = '<div class="group_info"> Quan hệ gia đình</div><div id="fgm_node_article_form_group_qhgd_banthan-add-more-wrapper"><h3> Về bản thân: Cha, Mẹ, Vợ (hoặc chồng), các con, anh chị em ruột</h3>';
    $form['fgm_node_article_form_group_benvo']['#prefix'] = '<div id="fgm_node_article_form_group_benvo-add-more-wrapper"><h3> Về bên vợ (hoặc chồng): Cha, Mẹ, anh chị em ruột</h3>';
      $form['field_xa']['#prefix'] = '<div class="clrb" style="height: 20px"></div><h3 class="h3-float">Nơi sinh: </h3>';
      $form['field_xa_que']['#prefix'] = '<h3 class="h3-float"> Quê quán: </h3>';
      $form['fgm_node_article_form_group_daotao']['#prefix'] = '<div id="fgm_node_article_form_group_daotao-add-more-wrapper"><div class="group_info">  Đào tạo, bồi dưỡng về chuyên môn, nghiệp vụ, lý luận chính trị, ngoại ngữ, tin học</div>';
      $form['fgm_node_article_form_group_daotao']['#suffix'] ='</div><h4>Ghi chú: Hình thức đào tạo: Chính quy, tại chức, chuyên tu, bồi dưỡng ..../ Văn bằng: TSKH, TS, Ths, Cử nhân, Kỹ sư ............</h4>';

      $form['fgm_node_article_form_group_congtac']['#prefix'] ='<div id="fgm_node_article_form_group_congtac-add-more-wrapper"><div class="group_info">  Tóm tắt quá trình công tác</div>';
      if(arg(2) == 'info') {
          if(!isset($form_state['build_info']['files'])){
              $form_state['build_info']['files'] = array("menu" => "modules/node/node.pages.inc");
          }
          $form['field_uid']['#access'] = false;
          $form['fgm_node_article_form_group_chiteu']['#access'] = false;
          $form['field_phong_ban']['und']['#default_value'][0] = nhansu_list_phong_ban_default();
      }
      if(arg(2) == 'kpi') {
          $form['field_ngaydang']['#access'] = FALSE;
          if(!isset($form_state['build_info']['files'])){
              $form_state['build_info']['files'] = array("menu" => "modules/node/node.pages.inc");
          }
          $form['field_is_poster']['#access'] = FALSE;
          $form['fgm_node_article_form_group_chiteu']['#access'] = true;
          $chi_tieu = $form['field_chiteu']['und']['#default_value'];
          $node_text = nhansu_kpi_get_muctieu_text();
          foreach($chi_tieu as $k => $data) {
              $form['field_muctieu']['und'][$k]['#access'] = false;
              if(in_array($data,$node_text)) {
                  $form['fgm_node_article_form_group_chiteu']['fields']['items'][$k]['field_muctieu']['und']['value']['#default_value'] = 'Hoàn thành';
                  $form['fgm_node_article_form_group_chiteu']['fields']['items'][$k]['field_toithieu']['und']['value']['#default_value'] = 'Hoàn thành';
                  $giatri_tt = $form['fgm_node_article_form_group_chiteu']['fields']['items'][$k]['field_thuc_hien']['und']['value']['#default_value'];
                  if($giatri_tt == 1 || $giatri_tt == 'Yes') {
                      $form['fgm_node_article_form_group_chiteu']['fields']['items'][$k]['field_thuc_hien']['und']['value']['#default_value'] = 'Yes';
                  }
                  else {
                      $form['fgm_node_article_form_group_chiteu']['fields']['items'][$k]['field_thuc_hien']['und']['value']['#default_value'] = 'No';
                  }
              }
          }
      }
    }
}

function nhansu_form_node_form_alter(&$form, &$form_state) {
    if(arg(2) == 'kpi') {
        field_group_hide_field_groups($form, array('group_soyeu'));
    }
}

function nhansu_list_node_term() {
    $tid = arg(2);
    $node = taxonomy_select_nodes($tid);
    print json_encode($node);
    exit;

}
function nhansu_list_nhom_chitieu() {
    $name = 'nhom_chiteu';
    $myvoc = taxonomy_vocabulary_machine_name_load($name);
    $tree = taxonomy_get_tree($myvoc->vid);
    foreach ($tree as $term) {
        $row[$term->tid] = $term -> name;
    }
    return $row;

}

function nhansu_list_node_kpi() {
    $query = db_query("SELECT nid,title FROM {node} WHERE type =:type",array(':type' => 'kpi'));
    foreach($query as $result) {
        $row[$result->nid] = $result -> title;
        $rows[] = $row;
    }
    return $rows;
}

function nhansu_get_kpi() {
    $nid = arg(1);
    $node = node_load($nid);
    $dv = '';
    $ts = '';
    $mt = '';
    $th = '';
    if(isset($node ->field_donvi_kpi['und'][0]['value']))
        $dv = $node ->field_donvi_kpi['und'][0]['value'];
    if(isset($node ->field_trongso_kpi['und'][0]['value']))
        $ts = $node ->field_trongso_kpi['und'][0]['value'];
    if(isset($node ->field_muctieu_kpi['und'][0]['value']))
        $mt = $node ->field_muctieu_kpi['und'][0]['value'];
    if(isset($node ->field_toithieu_kpi['und'][0]['value']))
        $th = $node ->field_toithieu_kpi['und'][0]['value'];
    $row  = array(
        '0' => $dv,
        '1' => $ts,
        '2' => $th,
        '3' => $mt,
    );
    print json_encode($row);
   exit;
}

function nhansu_list_phong_ban() {
    $name = 'phongban';
    $myvoc = taxonomy_vocabulary_machine_name_load($name);
    $tree = taxonomy_get_tree($myvoc->vid);
    foreach ($tree as $term) {
        $row[$term->tid] = $term -> name;
    }
    return $row;
}

function nhansu_list_phong_ban_default() {
    $uid = arg(1);
    $user = user_load($uid);
    $tid = $user ->field_phongban['und'][0]['tid'];
    return $tid;
}

function nhansu_nid_to_uid ($id) {
    $query = db_query("SELECT field_gan_cho_uid FROM {field_data_field_gan_cho} WHERE entity_id =:nid",array(":nid" => $id));
    foreach($query as $row) {
        $uid = $row -> field_gan_cho_uid;
    }
    return $uid;
}

function nhansu_uid_to_nid ($id) {
    $query = db_query("SELECT entity_id FROM {field_data_field_gan_cho} WHERE field_gan_cho_uid =:uid",array(":uid" => $id));
    foreach($query as $row) {
        $nid = $row -> entity_id;
    }
    return $nid;
}


function nhansu_node_update($node) {
    if($node -> type == 'article') {
       if(arg(2) == 'info') {
            $phong_ban = $node ->field_phong_ban['und'][0]['value'];
            $uid = arg(1);
            $account = user_load($uid); // Loading account
            $edit = array(
                'field_phongban' => array(
                    'und' => array(
                        0 => array(
                            'tid' => $phong_ban,
                        ),
                    ),
                ),
            );
           user_save($account, $edit);
       }
       drupal_goto('nhanvien/'.arg(1).'/info');
    }
    if($node ->type == 'giao_kpi') {
        drupal_goto('nhanvien/'.$node->field_uid['und'][0]['value'].'/kpi');
    }
    if($node ->type == 'kpi') {
        drupal_goto('caidat');
    }
}


function nhansu_node_presave($node) {
    if($node -> type == 'article') {

    }
}

function nhansu_get_nid_from_uid($uid = null,$type,$from = null,$to = null,$loc = null,$cac_quy = null,$nam_quy = null,$phong_ban = null,$nhan_vien = null) {
   $role = nhansu_kpi_check_user();
    if(isset($_GET['loc_theo'])) {
        $and = "";
        if(isset($_GET['loc_theo'])) {
            if($_GET['loc_theo'] == 0) {
                if(isset($_GET['from_time']) && !empty($_GET['from_time'])) {
                    $from = strtotime($_GET['from_time']);
                    $to = strtotime($_GET['to_time']);
                    $and .= ' AND nv.timestamp >= '.$from.' AND nv.timestamp <= '.$to;
                }
            }
            else {
                  if(isset($_GET['cac_quy']) && !empty($_GET['cac_quy'])) {
                      $time = nhansu_kpi_get_time_from_quy($_GET['cac_quy'],$_GET['nam_quy']);
                      $and .= ' AND nv.timestamp >= '.$time['from'].' AND nv.timestamp <= '.$time['to'];
                  }
            }
        }
        if(isset($_GET['phong_ban'])&& !empty($_GET['phong_ban'])) {
            $and .= ' AND phong.field_phongban_tid = '.$_GET['phong_ban'];
        }
        if(isset($_GET['nhan_vien']) && !empty($_GET['nhan_vien'])) {
            $and .= ' AND nguoidung.field_uid_value = '.$_GET['nhan_vien'];
        }
        if($role == 3) {
            global $user;
            $and .= ' AND nguoidung.field_uid_value = '.$user ->uid;
        }
        $sql = "SELECT MAX(nv.vid) as vid,nv.nid AS nid FROM {node_revision} AS nv
        INNER JOIN {field_data_field_uid} AS nguoidung ON nguoidung.entity_id = nv.nid
        INNER JOIN {node} AS node ON node.nid = nv.nid
        INNER JOIN {field_data_field_phongban} AS phong ON phong.entity_id = nguoidung.field_uid_value
        AND node.type = '".$type."' " .$and."  GROUP BY nv.nid";
        $query = db_query($sql);
        $num = $query->rowCount();
        if($num != 0) {
            foreach($query as $data) {
                $row['nid'] = $data-> nid;
                $row['vid'] = $data-> vid;
                $nid[] = $row;
            }
        }
        else
            $nid = 0;
    }
    else {
        if($type == 'article') {
            $query = db_query("SELECT nod.nid as nid FROM {node} as nod INNER JOIN {field_data_field_uid} as nguoidung ON nod.nid = nguoidung.entity_id AND nod.type =:type AND nguoidung.field_uid_value =:uid",array(":type" =>$type,":uid" => $uid));
            foreach($query as $data) {
                $nid = $data -> nid;
            }
        }
        else {
            $query = db_query("SELECT max(nod.nid) as nid FROM {node} as nod
        INNER JOIN {field_data_field_uid} as nguoidung ON nod.nid = nguoidung.entity_id
        INNER JOIN {field_data_field_kpi_giao_tu} as tu ON nod.nid = tu.entity_id
        AND nod.type =:type AND nguoidung.field_uid_value =:uid AND (tu.field_kpi_giao_tu_value = :ngay OR tu.field_kpi_giao_tu_value<:time)",array(":type" =>$type,":uid" => $uid,":ngay" =>1286643600,":time" =>time()));
            foreach($query as $data) {
                $nid = $data->nid;
            }
        }
    }
    if($nid)
        return $nid;
    else
        return "0";
}

function nhansu_get_title_from_uid($uid) {
    $query = db_query("SELECT nod.title as title FROM {node} as nod INNER JOIN {field_data_field_uid} as nguoidung ON nod.nid = nguoidung.entity_id AND nod.type =:type AND nguoidung.field_uid_value =:uid",array(":type" =>'article',":uid" => $uid));
    $num = $query->rowCount();
    if($num == 0)
        $title = "";
    else {
        foreach($query as $data) {
            $title = $data -> title;
        }
    }
    return $title;
}

function nhansu_list_all_nid_giamdoc() {
    $query = db_query("SELECT node.nid as nid FROM {node} as node
                       INNER JOIN {field_data_field_kpi_giao_tu} AS tu ON node.nid = tu.entity_id
                       INNER JOIN {field_data_field_giao_kpi_den} AS den ON node.nid = den.entity_id
                       AND tu.field_kpi_giao_tu_value <:time AND den.field_giao_kpi_den_value >:time
                       ",array(":time" =>time()));
    foreach($query as $data) {
        $nid[] = $data->nid;
    }
    return $nid;
}
function nhansu_get_all_nhanvien() {
    $query = db_query("SELECT nod.title as title,nguoidung.field_uid_value AS id FROM {node} as nod INNER JOIN {field_data_field_uid} as nguoidung ON nod.nid = nguoidung.entity_id AND nod.type =:type ",array(":type" =>'article'));
    $num = $query->rowCount();
    if($num == 0)
        $title = "";
    else {
        foreach($query as $data) {
            $row[$data -> id] = $data -> title;
        }

    }
    return $row;
}