<?php

function nhansu_caidat_menu() {
    $items['caidat'] = array(
        'title' => 'Cài đặt hệ thống',
        'page callback' => 'nhansu_caidat_kpi',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['caidat/kpi'] = array(
        'title' => 'Cài đặt hệ thống',
        'page callback' => 'nhansu_caidat_kpi',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['caidat/kpi/admin/%/edit'] = array(
        'title' => 'Chỉnh sửa KPI',
        'page callback' => 'nhansu_caidat_edit_kpi',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['caidat/kpi/admin/%/view'] = array(
        'title' => '',
        'page callback' => 'nhansu_caidat_view_kpi',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['caidat/kpi/admin/add'] = array(
        'title' => 'Thêm mới KPI',
        'page callback' => 'nhansu_caidat_add_kpi',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );

//duong dan cho nhom chi tieu
    $items['caidat/nhom/admin/list'] = array(
        'title' => 'Thêm mới KPI',
        'page callback' => 'nhansu_caidat_nhom',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['caidat/nhom/admin/%/edit'] = array(
        'title' => '',
        'page callback' => 'nhansu_caidat_nhom_edit',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['caidat/nhom/admin/add'] = array(
        'title' => 'Thêm mới KPI',
        'page callback' => 'nhansu_caidat_add_nhom',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
//page phong ban
    $items['caidat/phongban'] = array(
        'title' => 'Cài đặt phòng ban',
        'page callback' => 'nhansu_caidat_phongban',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['caidat/phongban/add'] = array(
        'title' => 'Thêm phòng ban mới',
        'page callback' => 'nhansu_caidat_phongban_add',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['caidat/phongban/%/edit'] = array(
        'title' => 'Chỉnh sửa phòng ban',
        'page callback' => 'nhansu_caidat_phongban_edit',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
// cai dat cho trang user
    $items['caidat/user'] = array(
        'title' => 'Cài đặt user',
        'page callback' => 'nhansu_caidat_user',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['caidat/user/add'] = array(
        'title' => 'Thêm mới user',
        'page callback' => 'nhansu_caidat_user_add',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['caidat/user/%/edit'] = array(
        'title' => 'Chỉnh sửa user',
        'page callback' => 'nhansu_caidat_user_edit',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['caidat/user/%/view'] = array(
        'title' => 'Xem chi tiết user',
        'page callback' => 'nhansu_caidat_user_view',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['caidat/user/vaitro'] = array(
        'title' => 'Cài đặt user',
        'page callback' => 'nhansu_caidat_user_vaitro',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['nhanvien/%/hoso'] = array(
        'title' => 'Thông tin',
        'page callback' => 'nhansu_caidat_hoso',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['nhanvien/%/mota'] = array(
        'title' => 'Mô tả công việc',
        'page callback' => 'nhansu_caidat_hoso',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['nhanvien/%/nangluc'] = array(
        'title' => 'Năng lực nhân viên',
        'page callback' => 'nhansu_caidat_nangluc',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['nhanvien/%/daingo'] = array(
        'title' => 'Chế độ đãi ngộ',
        'page callback' => 'nhansu_caidat_daingo',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['nhanvien/%/condanh'] = array(
        'title' => 'Con đường công danh',
        'page callback' => 'nhansu_caidat_congdanh',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );

    return $items;
}

function nhansu_caidat_user_add() {
    drupal_set_title("Thêm mới user");
    $output = drupal_get_form('user_register_form');
    return $output;
}
function nhansu_caidat_user_edit() {
    $id = arg(2);
    $user = user_load($id);
    module_load_include('inc', 'user', 'user.pages');
    $output = drupal_get_form('user_profile_form', $user);
    return drupal_render($output);
}
function nhansu_caidat_phongban_add() {
    $vocabulary = taxonomy_vocabulary_load(1, FALSE);
    module_load_include('inc', 'taxonomy', 'taxonomy.admin');
    drupal_set_title("Thêm mới phòng ban");
    $output = drupal_get_form('taxonomy_form_term',array(), $vocabulary);
    return $output;
}
function nhansu_caidat_phongban_edit() {
    $id = arg(2);
    module_load_include('inc', 'taxonomy', 'taxonomy.admin');
    $term = taxonomy_term_load($id);
    drupal_set_title("Chỉnh sửa phòng ban");
    $output = drupal_get_form('taxonomy_form_term', $term);
    return $output;
}

function nhansu_caidat_nhom_edit() {
    $id = arg(3);
    module_load_include('inc', 'taxonomy', 'taxonomy.admin');
    $term = taxonomy_term_load($id);
    drupal_set_title("Chỉnh sửa nhóm chỉ tiêu");
    $output = drupal_get_form('taxonomy_form_term', $term);
    return $output;
}
function nhansu_caidat_nhom() {
    drupal_set_title("Danh sách nhóm chỉ tiêu");
    $output = views_embed_view('nhom_chitieu','default');
    return $output;

}
function nhansu_caidat_add_nhom () {
    $vocabulary = taxonomy_vocabulary_load(4, FALSE);
    module_load_include('inc', 'taxonomy', 'taxonomy.admin');
    drupal_set_title("Thêm mới nhóm chỉ tiêu");
    $output = drupal_get_form('taxonomy_form_term',array(), $vocabulary);
    return $output;
}
function nhansu_caidat_view_kpi() {
    $node = node_load(arg(3));
    $view = node_view($node);
    return $view;
}
function nhansu_caidat_edit_kpi() {
    $id = arg(3);
    module_load_include('inc', 'node', 'node.pages');
    $node = node_load($id);
    $form = node_page_edit($node);
    return $form;
}
function nhansu_caidat_add_kpi() {
    module_load_include('inc', 'node', 'node.pages');
    $form = node_add('kpi');
    drupal_set_title("Tạo KPI mới");
    return drupal_render($form);

}

function nhansu_caidat_user_vaitro() {
    $form = drupal_get_form("user_admin_roles");
    $ouput = drupal_render($form);
    return $ouput;
}
function nhansu_caidat_nangluc() {
    return "";
}
function nhansu_caidat_daingo() {
    return "";
}
function nhansu_caidat_congdanh() {
    return "";
}
function nhansu_caidat_user(){
   drupal_set_title("Danh sách user");
    $output = views_embed_view('caidat_user','default');
    return $output;
}

function nhansu_caidat_phongban() {
    $output = views_embed_view('phong_ban','default');
    return $output;
}

function nhansu_caidat_hoso() {
    drupal_set_title("Mô tả công việc");
    return "";
}

function nhansu_caidat_kpi() {
    drupal_set_title("Danh sách KPI");
    $output = views_embed_view('thu_vien_kpi','default');
    return $output;
}

function nhansu_caidat_form_alter(&$form, &$form_state, $form_id) {
    if($form_id =='user_register_form') {

    }
    if(arg(1) == "nhom") {
        $form['name']['#title'] ="Tên nhóm chỉ tiêu";
        $form['description']['#access'] = FALSE;
    }
    if(arg(1) == "phongban"){
        $form['name']['#title'] ="Tên phòng ban";
        $form['description']['#access'] = FALSE;
    }
    if($form_id == 'kpi_node_form') {
        if(is_numeric(arg(3))) {
            $form['field_congthuc']['#access'] = FALSE;
        }
    }
    if(arg(0) =='caidat' && arg(1) =='user') {
        $form['picture']['#access'] = FALSE;
        $form['Timezone']['#access'] = FALSE;
    }
}
