<?php

/**
 * Implement hook_init
 */

function nhansu_user_user_insert(&$edit, $account, $category) {
    $uid = $account -> uid;
    $node_hoso = new stdClass();
    $node_hoso->type = 'article';
    $node_hoso->status = 1;
    $node_hoso->timestamp = strtotime("now");
    $node_hoso->uid = 1;
    $node_hoso->title = $account->name;
    $node_hoso->comment = 2;
    $node_hoso->promote = 1;
    $node_hoso->field_uid['und'][0]['value'] = $uid;
    node_save($node_hoso);

    $node_giao_kpi = new stdClass();
    $node_giao_kpi->type = 'giao_kpi';
    $node_giao_kpi->status = 1;
    $node_giao_kpi->timestamp = strtotime("now");
    $node_giao_kpi->uid = 1;
    $node_giao_kpi->title = $account->name;
    $node_giao_kpi->comment = 2;
    $node_giao_kpi ->field_kpi_giao_tu['und'][0]['value'] = 1286643600;
    $node_giao_kpi->promote = 1;
    $node_giao_kpi->field_uid['und'][0]['value'] = $uid;
    node_save($node_giao_kpi);
}

function nhansu_user_check_time($uid) {
    $id = nhansu_get_nid_from_uid($uid,"giao_kpi");
    $node = node_load($id);
    $tu = $node -> field_kpi_giao_tu['und'][0]['value'];

    if($tu == 1286643600) {
        $output = '<a href ="../nhanvien/'.$uid.'/kpi"> Chưa giao</a>';
    }
    else {
        $output = '<a href ="../nhanvien/'.$uid.'/kpi"> Đã giao</a>';
    }
    return $output;
}