<?php
/**
 * @param $form
 * @param $form_state
 * @param $form_id
 * Implement hook form alter
 */

function ns_hook_form_alter(&$form, &$form_state, $form_id) {

    if($form_id == 'kpi_node_form' && arg(1) == 'kpi') {
        global $base_url;
        $form['actions']['delete']['#access'] = FALSE;
        $delete ="<a href='".$base_url."/caidat/kpi/admin/".arg(3)."/delete'>Delete</a>";
        $form['actions']['submit']["#suffix"] = $delete;
    }
    if($form_id == "giao_kpi_node_form") {
        if(arg(2) == 'kpi') {
            global $user;
            if($user -> uid == arg(1)) {
                $form['fgm_node_giao_kpi_form_group_giaokpi']['#prefix'] = '<div id="fgm_node_giao_kpi_form_group_giaokpi-add-more-wrapper" class="ex_me">';
            }
            $add = arg(3);
            $form['title']['#access'] = FALSE;
            $form['field_giaokpi_nguoigiao']['#access'] = FALSE;
            if(!isset($form_state['build_info']['files'])){
                $form_state['build_info']['files'] = array("menu" => "modules/node/node.pages.inc");
            }
            if(isset($add) && $add =='add') {
                $form['title']['#access'] = FALSE;
            }
        }
    }
    if($form_id == 'article_node_form') {
        if(arg(3) =='mota' || arg(3) == null) {
            $form['field_uid']['#access'] = false;
            $form['fgm_node_article_form_group_nang_luc']['#access'] = false;
        }
        $check = nhansu_kpi_check_user();
        if($check == 3) {
            $form['actions']['#access'] = false;
            $form['actions']['#access'] = false;
            $form['field_gan_cho']['#access'] = false;
            $form['field_giaokpi_nguoigiao']['#access'] = false;
        }
        $form['field_nghenghiep']['#prefix'] ='<div class="group_info">Thông tin về chuyên môn nghiệp vụ:</div>';
        $form['field_image']['#prefix'] = '<div class="group_info">Thông tin cơ bản:</div>';
        $form['field_lyluan_chinhtri']['#prefix'] = '<div class="group_info">Chính trị:</div>';
        $form['field_ngoaingu']['#prefix'] = '<div class="group_info">Tin học/Ngoại ngữ:</div>';
        $form['field_suckhoe']['#prefix'] = '<div class="group_info">Sức khỏe:</div>';


        $form['fgm_node_article_form_group_qhgd_banthan']['#prefix'] = '<div class="group_info"> Quan hệ gia đình</div><div id="fgm_node_article_form_group_qhgd_banthan-add-more-wrapper"><h3> Về bản thân: Cha, Mẹ, Vợ (hoặc chồng), các con, anh chị em ruột</h3>';
        $form['fgm_node_article_form_group_benvo']['#prefix'] = '<div id="fgm_node_article_form_group_benvo-add-more-wrapper"><h3> Về bên vợ (hoặc chồng): Cha, Mẹ, anh chị em ruột</h3>';
        $form['field_xa']['#prefix'] = '<div class="clrb" style="height: 20px"></div><h3 class="h3-float">Nơi sinh: </h3>';
        $form['field_xa_que']['#prefix'] = '<h3 class="h3-float"> Quê quán: </h3>';
        $form['fgm_node_article_form_group_daotao']['#prefix'] = '<div id="fgm_node_article_form_group_daotao-add-more-wrapper"><div class="group_info">  Đào tạo, bồi dưỡng về chuyên môn, nghiệp vụ, lý luận chính trị, ngoại ngữ, tin học</div>';
        $form['fgm_node_article_form_group_daotao']['#suffix'] ='</div><h4>Ghi chú: Hình thức đào tạo: Chính quy, tại chức, chuyên tu, bồi dưỡng ..../ Văn bằng: TSKH, TS, Ths, Cử nhân, Kỹ sư ............</h4>';

        $form['fgm_node_article_form_group_congtac']['#prefix'] ='<div id="fgm_node_article_form_group_congtac-add-more-wrapper"><div class="group_info">  Tóm tắt quá trình công tác</div>';
        if(arg(2) == 'info') {
            if(!isset($form_state['build_info']['files'])){
                $form_state['build_info']['files'] = array("menu" => "modules/node/node.pages.inc");
            }
            $form['field_uid']['#access'] = false;
            $form['fgm_node_article_form_group_chiteu']['#access'] = false;
            $form['field_phong_ban']['und']['#default_value'][0] = nhansu_list_phong_ban_default();
        }
        if(arg(2) == 'kpi') {
            $form['field_ngaydang']['#access'] = FALSE;
            if(!isset($form_state['build_info']['files'])){
                $form_state['build_info']['files'] = array("menu" => "modules/node/node.pages.inc");
            }
            $form['field_is_poster']['#access'] = FALSE;
            $form['fgm_node_article_form_group_chiteu']['#access'] = true;
            $chi_tieu = $form['field_chiteu']['und']['#default_value'];
            $node_text = nhansu_kpi_get_muctieu_text();
            foreach($chi_tieu as $k => $data) {
                $form['field_muctieu']['und'][$k]['#access'] = false;
                if(in_array($data,$node_text)) {
                    $form['fgm_node_article_form_group_chiteu']['fields']['items'][$k]['field_muctieu']['und']['value']['#default_value'] = 'Hoàn thành';
                    $form['fgm_node_article_form_group_chiteu']['fields']['items'][$k]['field_toithieu']['und']['value']['#default_value'] = 'Hoàn thành';
                    $giatri_tt = $form['fgm_node_article_form_group_chiteu']['fields']['items'][$k]['field_thuc_hien']['und']['value']['#default_value'];
                    if($giatri_tt == 1 || $giatri_tt == 'Yes') {
                        $form['fgm_node_article_form_group_chiteu']['fields']['items'][$k]['field_thuc_hien']['und']['value']['#default_value'] = 'Yes';
                    }
                    else {
                        $form['fgm_node_article_form_group_chiteu']['fields']['items'][$k]['field_thuc_hien']['und']['value']['#default_value'] = 'No';
                    }
                }
            }
        }
    }
}

function ns_hook_preprocess_html(&$vars) {
    global $user;
    $uid = $user ->uid;
    if($uid == arg(1)) {
        $vars['classes_array'][] = "ex_me";
    }
}