<?php
/**
 * @param $form
 * @param $form_state
 * @param $form_id
 * Implement hook form alter
 */

function ns_hook_form_alter(&$form, &$form_state, $form_id) {

    if($form_id == 'kpi_node_form' && arg(1) == 'kpi') {
        global $base_url;
        $form['actions']['delete']['#access'] = FALSE;
        $delete ="<a href='".$base_url."/caidat/kpi/admin/".arg(3)."/delete'>Delete</a>";
        $form['actions']['submit']["#suffix"] = $delete;
    }
    if($form_id == "giao_kpi_node_form") {
        if(arg(2) == 'kpi') {
            global $user;
            if($user -> uid == arg(1)) {
                $form['fgm_node_giao_kpi_form_group_giaokpi']['#prefix'] = '<div id="fgm_node_giao_kpi_form_group_giaokpi-add-more-wrapper" class="ex_me">';
            }
            $add = arg(3);
            $form['title']['#access'] = FALSE;
            $form['field_giaokpi_nguoigiao']['#access'] = FALSE;
            if(!isset($form_state['build_info']['files'])){
                $form_state['build_info']['files'] = array("menu" => "modules/node/node.pages.inc");
            }
            if(isset($add) && $add =='add') {
                $form['title']['#access'] = FALSE;
            }
        }
    }
    if($form_id == 'article_node_form') {
        if(arg(2) == 'hoso'){
            if(!isset($form_state['build_info']['files'])){
                $form_state['build_info']['files'] = array("menu" => "modules/node/node.pages.inc");
            }
            $form['field_phong_ban']['#access'] = false;
            if(arg(3) =='mota' || arg(3) == null) {
                $form['field_uid']['#access'] = false;
                $form['fgm_node_article_form_group_nang_luc']['#access'] = false;
                $form['fgm_node_article_form_group_lotrinh']['#access'] = false;
                $form['fgm_node_article_form_group_daingo']['#access'] = false;
                $form['fgm_node_article_form_group_chuyen_mon']['#access'] = false;

            }
            if(arg(3) =='nangluc') {
                $form['fgm_node_article_form_group_nang_luc']['#prefix'] = '<div id="fgm_node_article_form_group_nang_luc-add-more-wrapper"><h3>Trình độ cơ bản</h3>';
                $form['fgm_node_article_form_group_chuyen_mon']['#prefix'] = '<div id="fgm_node_article_form_group_chuyen_mon-add-more-wrapper"><h3>Trình độ chuyên môn</h3>';
                $form['field_uid']['#access'] = false;
                $form['fgm_node_article_form_group_daingo']['#access'] = false;
                $form['fgm_node_article_form_group_lotrinh']['#access'] = false;
            }
            if(arg(3) =='daingo') {
                $form['field_uid']['#access'] = false;
                $form['fgm_node_article_form_group_nang_luc']['#access'] = false;
                $form['fgm_node_article_form_group_lotrinh']['#access'] = false;
                $form['fgm_node_article_form_group_chuyen_mon']['#access'] = false;
            }
            if(arg(3) =='congdanh') {
                $form['field_uid']['#access'] = false;
                $form['fgm_node_article_form_group_nang_luc']['#access'] = false;
                $form['fgm_node_article_form_group_chuyen_mon']['#access'] = false;
                if(!isset($form_state['build_info']['files'])){
                    $form_state['build_info']['files'] = array("menu" => "modules/node/node.pages.inc");
                }
            }
        }
        $check = nhansu_kpi_check_user();
        if($check == 3) {
            $form['actions']['#access'] = false;
            $form['actions']['#access'] = false;
            $form['field_gan_cho']['#access'] = false;
            $form['field_giaokpi_nguoigiao']['#access'] = false;
        }
        $form['field_nghenghiep']['#prefix'] ='<div class="group_info">Thông tin về chuyên môn nghiệp vụ:</div>';
        $form['field_image']['#prefix'] = '<div class="group_info">Thông tin cơ bản:</div>';
        $form['field_lyluan_chinhtri']['#prefix'] = '<div class="group_info">Chính trị:</div>';
        $form['field_ngoaingu']['#prefix'] = '<div class="group_info">Tin học/Ngoại ngữ:</div>';
        $form['field_suckhoe']['#prefix'] = '<div class="group_info">Sức khỏe:</div>';


        $form['fgm_node_article_form_group_qhgd_banthan']['#prefix'] = '<div class="group_info"> Quan hệ gia đình</div><div id="fgm_node_article_form_group_qhgd_banthan-add-more-wrapper"><h3> Về bản thân: Cha, Mẹ, Vợ (hoặc chồng), các con, anh chị em ruột</h3>';
        $form['fgm_node_article_form_group_benvo']['#prefix'] = '<div id="fgm_node_article_form_group_benvo-add-more-wrapper"><h3> Về bên vợ (hoặc chồng): Cha, Mẹ, anh chị em ruột</h3>';
        $form['field_xa']['#prefix'] = '<div class="clrb" style="height: 20px"></div><h3 class="h3-float">Nơi sinh: </h3>';
        $form['field_xa_que']['#prefix'] = '<h3 class="h3-float"> Quê quán: </h3>';
        $form['fgm_node_article_form_group_daotao']['#prefix'] = '<div id="fgm_node_article_form_group_daotao-add-more-wrapper"><div class="group_info">  Đào tạo, bồi dưỡng về chuyên môn, nghiệp vụ, lý luận chính trị, ngoại ngữ, tin học</div>';
        $form['fgm_node_article_form_group_daotao']['#suffix'] ='</div><h4>Ghi chú: Hình thức đào tạo: Chính quy, tại chức, chuyên tu, bồi dưỡng ..../ Văn bằng: TSKH, TS, Ths, Cử nhân, Kỹ sư ............</h4>';

        $form['fgm_node_article_form_group_congtac']['#prefix'] ='<div id="fgm_node_article_form_group_congtac-add-more-wrapper"><div class="group_info">  Tóm tắt quá trình công tác</div>';
        if(arg(2) == 'info') {
            if(!isset($form_state['build_info']['files'])){
                $form_state['build_info']['files'] = array("menu" => "modules/node/node.pages.inc");
            }
            $form['field_uid']['#access'] = false;
            $form['fgm_node_article_form_group_chiteu']['#access'] = false;
            $form['field_phong_ban']['und']['#default_value'][0] = nhansu_list_phong_ban_default();

            $form['fgm_node_article_form_group_nang_luc']['#access'] = false;
            $form['fgm_node_article_form_group_lotrinh']['#access'] = false;
            $form['fgm_node_article_form_group_daingo']['#access'] = false;
            $form['fgm_node_article_form_group_chuyen_mon']['#access'] = false;
        }
    }
}

/**
 * @param $vars
 * Them class vao the body
 */
function ns_hook_preprocess_html(&$vars) {
    global $user;
    $uid = $user ->uid;
    $role = nhansu_kpi_check_user();
    if($uid == arg(1)) {
        $vars['classes_array'][] = "ex_me";
    }
    if($role == 3) {
        $vars['classes_array'][] = "nhanvien";
    }
}


function ns_hook_form_node_form_alter(&$form, &$form_state) {
    if(arg(2) == 'hoso') {
        if(arg(3) == null || arg(3) == 'mota') {
            field_group_hide_field_groups($form, array('group_soyeu','group_daingo'));
        }
        if(arg(3) == 'nangluc') {
            field_group_hide_field_groups($form, array('group_soyeu','group_mota_cv','group_daingo'));
        }
        if(arg(3) == 'daingo') {
            field_group_hide_field_groups($form, array('group_soyeu','group_mota_cv'));
        }
        if(arg(3) == 'congdanh') {
            field_group_hide_field_groups($form, array('group_soyeu','group_mota_cv','group_daingo'));
        }
    }
    if(arg(2) == 'info') {
        field_group_hide_field_groups($form, array('group_mota_cv','group_daingo'));
    }
}