<?php

function nhansu_kpi_init() {
    drupal_add_js(drupal_get_path('module','nhansu_kpi').'/js/kpi.js');
}


function nhansu_kpi_menu() {
    $items['load/%'] = array(
        'title' => 'Thông tin',
        'page callback' => 'nhansu_chart_data_load',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['danhgia_kpi/%/%'] = array(
        'title' => 'Thông tin',
        'page callback' => 'nhansu_chart_data_load_danhgia',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    return $items;
}
function nhansu_kpi_block_info() {
    $blocks['kpi_user'] = array(
        'info' => t('KPI cho user'),
    );
    return $blocks;
}
function nhansu_kpi_block_view($delta = '') {

    $block = array();
    switch ($delta) {
        case 'kpi_user':
            $block['content'] = nhansu_kpi_giao_user();
            break;
    }
    return $block;
}
function nhansu_kpi_kiemsoat() {
  drupal_set_title("Kiểm soát KPI");
  return "";
}
function nhansu_kpi_danhgia() {
    drupal_set_title("Đánh giá KPI");
    $nid = nhansu_get_all_nid();
    foreach($nid as $data) {
        $node = node_load($data);
        $count = $node-> field_giaokpi_chi;
        if(!empty($count)) {
            foreach($count['und'] as $k => $result) {
                $node_dl = node_load($result['value']);
                $title = $node_dl -> title;
                if(!empty($node->field_giaokpi_hoanthanh)) {
                    $ht_field = $node->field_giaokpi_hoanthanh['und'][$k]['value'];
                }
                else{
                    $ht_field = 0;
                }
                if(!empty($node->field_giaokpi_thuchien)){
                    $thuc_hien = $node->field_giaokpi_thuchien['und'][$k]['value'];
                }
                else {
                    $thuc_hien = 0;
                }
                if(!empty($node -> field_giaokpi_trong)) {
                    $trong_so = $node->field_giaokpi_trong['und'][$k]['value'];
                }
                else {
                    $trong_so = 0;
                }
                $toi_thieu = $node->field_giaokpi_toi['und'][$k]['value'];
                $muc_tieu = $node->field_giaokpi_muctieu['und'][$k]['value'];

                $chitiet['title'] = $title;
                $chitiet['trong_so'] = $trong_so;
                $chitiet['toi_thieu'] = $toi_thieu;
                $chitiet['muc_tieu'] = $muc_tieu;
                $chitiet['thuc_hien'] = $thuc_hien;
                $chitiet["ht"] = $ht_field;
                $rows[] = $chitiet;
            }
        }
    }

    $output = "";
    $form = drupal_get_form('nhansu_chart_filer_time');
    $output .= '<div class="filter_time">'.drupal_render($form).'</div>';
    $header = array('KPI',"Trọng số","Mục tiêu","Tối thiểu","Thực hiện",'Hoàn thành');
    $output .= '<div class="noidung">'.theme('table', array('header' => $header,   'rows' => $rows )).'</div>';
    $output .= '<div class="print_ex"><a onclick="chart_kpi_print(123)" href="#">Print</a> </div>';
    return $output;
}

function nhansu_chart_data_load_danhgia() {
    $tid = arg(1);
    $nid = arg(2);
    $dulieu = nhansu_data_table($tid,$nid);
    $num = count($dulieu);
    $tong = 0;
    foreach($dulieu as $content) {
        $giatri = $content['ht'];
        $giatri = trim(str_replace("%","",$giatri));
        $tong = $tong + $giatri;
    }
    $tong = $tong.'%';
    $arr_pb =   nhansu_data_table($tid,$nid)+ array($num => array("title" => "Tổng","ht" =>$tong)) ;
    $table = '<h2>Chỉ tiêu KPI</h2>'.theme('table', array('header' => array("KPI","Hoàn thành"),   'rows' => $arr_pb));
    $content = nhansu_chart_data($tid,$nid);
    $list_node = nhansu_kpi_list_node_in_phong($tid);
    print json_encode(array('status' => TRUE, 'data' => $content, 'right' =>$table,'nid' =>$list_node));
    exit;
}

function nhansu_chart_data_load() {
    $tid = arg(1);
    $uid = nhansu_kpi_uid_in_phong($tid);
   // print_r($uid);
    print json_encode($uid);
    exit;
}

function nhansu_kpi_get_all() {
   $nid = nhansu_get_all_nid();
    foreach($nid as $content) {
        $node = node_load($content['nid']);
        $vid = $node -> vid;
        $count = $node-> field_giaokpi_chi;
        $ht = 0;
        if(!empty($count))  {
            foreach($count['und'] as $k => $result) {

                $hoan_thanh = trim($node -> field_giaokpi_hoanthanh['und'][$k]['value']);
                $hoan_thanh = substr($hoan_thanh,0,-1);
                $ht = $ht + $hoan_thanh;
                //table ben phai
                $node_dl = node_load($result['value']);
                $title = $node_dl -> title;
                if(!empty($node->field_giaokpi_hoanthanh)) {
                    $ht_field = $node->field_giaokpi_hoanthanh['und'][$k]['value'];
                }
                else{
                    $ht_field = 0;
                }
                if(!empty($node->field_giaokpi_thuchien)){
                    $thuc_hien = $node->field_giaokpi_thuchien['und'][$k]['value'];
                }
                else {
                    $thuc_hien = 0;
                }
                if(!empty($node -> field_giaokpi_trong)) {
                    $trong_so = $node->field_giaokpi_trong['und'][$k]['value'];
                }
                else {
                    $trong_so = 0;
                }
                $toi_thieu = $node->field_giaokpi_toi['und'][$k]['value'];
                $muc_tieu = $node->field_giaokpi_muctieu['und'][$k]['value'];
                $row['title'] = '<a href="#chart_div2"><span toi_thieu="'.$toi_thieu.'" thuc_hien="'.$thuc_hien.'" muc_tieu ="'               .$muc_tieu.'" class= "ckpi_ad" rel ="'.$k.'" id = "kpi_'.$vid.'" alt = "'.$vid.'">' .$title.'</span></a>';
                $row['ht'] = $ht_field;
                $chitiet['title'] = $title;
                $chitiet['trong_so'] = $trong_so;
                $chitiet['toi_thieu'] = $toi_thieu;
                $chitiet['muc_tieu'] = $muc_tieu;
                $chitiet['thuc_hien'] = $thuc_hien;
                $chitiet["ht"] = $ht_field;
                $rows[] = $row;
            }}
    }


}

function nhansu_kpi_check_user() {
    global $user;
    $role= $user->roles;
    if(isset($role[3]) || isset($role[4]) || isset($role[5]))
        return 1;
    elseif(isset($role[6]))
        return 2;
    else
        return 3;
}

function nhansu_kpi_get_phongban($uid) {
    $query = db_query("SELECT field_phongban_tid FROM {field_data_field_phongban} WHERE entity_id =:uid", array(':uid' => $uid));
    foreach($query as $data) {
       $phong = $data ->field_phongban_tid;
    }
    return $phong;
}

function nhansu_kpi_uid_in_phong($tid) {
    $query = db_query("SELECT entity_id FROM {field_data_field_phongban} WHERE field_phongban_tid =:tid", array(':tid' => $tid));
    foreach($query as $data) {
        $uid[] = $data ->entity_id;
    }
    return $uid;
}

function nhansu_kpi_list_node_in_phong($tid) {
    $uid = nhansu_kpi_uid_in_phong($tid);
    foreach($uid as $data) {
        $nid[] = nhansu_uid_to_nid($data['uid']);

    }
    return $nid;
}

function nhansu_kpi_get_all_user($uid) {
    $phong = nhansu_kpi_get_phongban($uid);
    $query = db_query("SELECT entity_id FROM {field_data_field_phongban} WHERE field_phongban_tid =:term", array(':term' => $phong));
    foreach($query as $data) {
        $row = $data -> entity_id ;
        $rows[] = nhansu_uid_to_nid($row);
    }
    return $rows;
}
function nhansu_kpi_get_all_user_tid($tid) {
    $query = db_query("SELECT entity_id FROM {field_data_field_phongban} WHERE field_phongban_tid =:term", array(':term' => $tid));
    $num_of_results = $query->rowCount();
    if($num_of_results > 0) {
        foreach($query as $data) {
            $row = $data -> entity_id ;
            $rows[] = nhansu_uid_to_nid($row);
        }
        return $rows;
    }
    else {
        return 1;
    }
}

function nhansu_kpi_get_muctieu_text() {
    $query = db_query("SELECT entity_id FROM {field_data_field_muctieu_kpi} WHERE field_muctieu_kpi_value LIKE :muctieu",array(':muctieu' => '%h%'));
    foreach($query as $data) {
        $row[] = $data->entity_id;
    }
    return $row;
}

function nhansu_kpi_get_all_node_in_phong() {
    global $user;
    $user_load = user_load($user->uid);
    $tid = $user_load->field_phongban['und'][0]['tid'];
    $uid = nhansu_kpi_uid_in_phong($tid);
    foreach($uid as $data) {
        $title = nhansu_get_title_from_uid($data['uid']);
        $res[$data['uid']] = $title;
    }
return $res;
}

function nhansu_kpi_get_all_nid_from_login() {
    $check = nhansu_kpi_check_user();
    if($check == 1) {
        $query = db_query("SELECT nid,title FROM {node} WHERE type =:type",array(":type" =>'article'));
        foreach($query as $data) {
            $nid[] = $data->nid;
        }
    }
    elseif($check == 2) {
        global $user;
        $nid =nhansu_kpi_get_all_user($user->uid);

    }
    else {
        global $user;
        $uid = $user ->uid;
        $nid[] = nhansu_uid_to_nid($uid);
    }
return $nid;
}
function nhansu_kpi_export_page($data) {
    $filename = 'ThongKeGiaVangNgay-' . date('d-m-Y') . '.xls';
    header('Content-Description: File Transfer');
    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename=' . $filename);
    header('Content-Transfer-Encoding: binary');
    header('Expires: 0');
    header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
    header('Pragma: public');
    echo "\xEF\xBB\xBF"; // UTF-8 BOM
    print $data;exit;
}

function nhansu_kpi_giao_user() {
    $nid = nhansu_get_nid_from_uid(arg(1),"giao_kpi");
    $node = node_load($nid);
    $output = '';
    $tu_ngay = $node-> field_kpi_giao_tu['und'][0]['value'];
    $den_ngay = $node -> field_giao_kpi_den['und'][0]['value'];
    $id_nguoigiao = $node -> field_giaokpi_nguoigiao;
    if(empty($id_nguoigiao)) {
      $uid_tp = nhansu_kpi_get_truong_phong(arg(1));
      $nguoi_giao = nhansu_get_title_from_uid($uid_tp);
    }
    else {
      $uid_tp = $node -> field_giaokpi_nguoigiao['und'][0]['value'];
      $nguoi_giao = nhansu_get_title_from_uid($uid_tp);
    }
    $nguoi_nhan = nhansu_get_title_from_uid(arg(1));
    $output .= '<div class="giao"><span>Người giao: </span>'.$nguoi_giao .'</div>';
    $output .= '<div class="giao"><span>Người nhận: </span>'.$nguoi_nhan .'</div>';
    $output .= '<div class="time"><span>Thời gian: </span><span>Từ ngày:</span>'.date("d/m/Y",$tu_ngay);
    $output .= '<span>   Đến ngày: </span>'.date("d/m/Y",$den_ngay);
    return $output;
}
function nhansu_kpi_create() {
    module_load_include('inc', 'node', 'node.pages');
    $form = node_add('giao_kpi');
    $title = nhansu_get_title_from_uid(arg(1));
    drupal_set_title("Giao KPI mới cho: ".$title);
    return drupal_render($form);
}

function nhansu_kpi_get_time_from_quy($quy,$nam = null) {
    if(isset($nam)) {
        $time_year = $nam;
    }
    else{
        $time_year = date("Y",time());
    }
    switch($quy) {
        case 1:
            $time['from'] = strtotime($time_year.'-01-01');
            $time['to'] = strtotime($time_year.'-03-30');
            break;
        case 2:
            $time['from'] = strtotime($time_year.'-04-01');
            $time['to'] = strtotime($time_year.'-06-30');
            break;
        case 3:
            $time['from'] = strtotime($time_year.'-07-01');
            $time['to'] = strtotime($time_year.'-09-30');
            break;
        case 4:
            $from = $time_year.'-10-01';
            $from = strtotime($from);
            $to = $time_year.'-12-31';
            $to = strtotime($to);
            $time['from'] = $from;
            $time['to'] = $to;
            break;
    }

    return $time;
}

function doanhthu_for_giamdoc() {
    $and = " AND nhom.field_giaokpi_nhom_value = 4 AND toithieu.delta = muctieu.delta AND thuchien.delta = muctieu.delta AND nhom.delta = muctieu.delta ";
    if(isset($_GET['loc_theo'])) {
        if($_GET['loc_theo'] == 0) {
            if(isset($_GET['from_time']) && !empty($_GET['from_time'])) {
                $from = strtotime($_GET['from_time']);
                $to = strtotime($_GET['to_time']);
                $and .= ' AND nv.timestamp >= '.$from.' AND nv.timestamp <= '.$to;
            }
        }
        else {
            if(isset($_GET['cac_quy']) && !empty($_GET['cac_quy'])) {
                $time = nhansu_kpi_get_time_from_quy($_GET['cac_quy'],$_GET['nam_quy']);
                $and .= ' AND nv.timestamp >= '.$time['from'].' AND nv.timestamp <= '.$time['to'];
            }
        }
        if(isset($_GET['phong_ban'])&& !empty($_GET['phong_ban'])) {
            $and .= ' AND phong.field_phongban_tid = '.$_GET['phong_ban'];
        }
        if(isset($_GET['nhan_vien']) && !empty($_GET['nhan_vien'])) {
            $and .= ' AND nguoidung.field_uid_value = '.$_GET['nhan_vien'];
        }
    }
    else {
        $and .= " AND nv.timestamp <= den.field_giao_kpi_den_value
                    AND nv.timestamp >= tu.field_kpi_giao_tu_value ";
    }
    $sql1 = " SELECT  MAX(nv.vid) as vid
                    FROM {field_revision_field_giaokpi_muctieu} AS muctieu
                    INNER JOIN {field_revision_field_giaokpi_nhom} AS nhom ON muctieu.revision_id = nhom.revision_id
                    INNER JOIN {field_revision_field_giaokpi_toi} AS toithieu ON toithieu.revision_id = nhom.revision_id
                    INNER JOIN {node_revision} as nv ON nv.vid = toithieu.revision_id
                    INNER JOIN {field_revision_field_kpi_giao_tu} AS tu ON tu.revision_id = toithieu.revision_id
                    INNER JOIN {field_revision_field_giao_kpi_den} AS den ON den.revision_id = tu.revision_id
                    INNER JOIN {field_data_field_uid} AS nguoidung ON nguoidung.entity_id = nv.nid
                    INNER JOIN {field_data_field_phongban} AS phong ON phong.entity_id = nguoidung.field_uid_value
                    INNER JOIN {field_revision_field_giaokpi_thuchien} AS thuchien ON thuchien.revision_id = den.revision_id
                    ".$and. " GROUP BY nv.nid";
    $query1 = db_query($sql1);
    foreach($query1 as $content) {
        $vid[] = $content->vid;
    }
    if(empty($vid))
        return 0;
    $vid = implode(', ', $vid);

    $sql = " SELECT SUM(muctieu.field_giaokpi_muctieu_value) as mtieu,SUM(toithieu.field_giaokpi_toi_value) as tthieu, SUM(thuchien.field_giaokpi_thuchien_value) as thien, MAX(nv.vid)
                    FROM {field_revision_field_giaokpi_muctieu} AS muctieu
                    INNER JOIN {field_revision_field_giaokpi_nhom} AS nhom ON muctieu.revision_id = nhom.revision_id
                    INNER JOIN {field_revision_field_giaokpi_toi} AS toithieu ON toithieu.revision_id = nhom.revision_id
                    INNER JOIN {node_revision} as nv ON nv.vid = toithieu.revision_id
                    INNER JOIN {field_revision_field_kpi_giao_tu} AS tu ON tu.revision_id = toithieu.revision_id
                    INNER JOIN {field_revision_field_giao_kpi_den} AS den ON den.revision_id = tu.revision_id
                    INNER JOIN {field_data_field_uid} AS nguoidung ON nguoidung.entity_id = nv.nid
                    INNER JOIN {field_data_field_phongban} AS phong ON phong.entity_id = nguoidung.field_uid_value
                    INNER JOIN {field_revision_field_giaokpi_thuchien} AS thuchien ON thuchien.revision_id = den.revision_id
                    WHERE nv.vid IN (".$vid.")". $and;
    $query = db_query($sql);
    foreach($query as $data) {

        $row['toi_thieu'] = $data ->tthieu ;
        $row['muc_tieu'] = $data-> mtieu ;
        $row['thuc_hien'] = $data ->thien ;

    }
    return $row;

}

function nhansu_kpi_get_truong_phong($uid) {
    $user = user_load($uid);
    $phong_ban = $user->field_phongban['und'][0]['tid'];
    $query = db_query("SELECT entity_id as uid FROM {field_data_field_phongban} as phongban WHERE phongban.field_phongban_tid =:phongb",array(":phongb" =>$phong_ban));
    foreach($query as $data) {
        $row[] = $data ->uid;
    }
    $sql = "SELECT uid FROM {users_roles} as role WHERE uid IN (".implode(', ', $row) .") AND rid = 6 ";
    $query2 = db_query($sql);
    foreach($query2 as $content) {
        $uid = $content ->uid;
    }
    return $uid;
}

function nhansu_kpi_nguoigiao() {
    $role = nhansu_kpi_check_user();

}